import { createSlice, PayloadAction } from '@reduxjs/toolkit';

export type ModelStatus =
  | 'not_downloaded'
  | 'downloading'
  | 'downloaded'
  | 'loading'
  | 'loaded';

export type BackendType = 'AUTO' | 'NPU' | 'GPU' | 'CPU';

export interface ModelInfo {
  id: string;
  name: string;
  tag: string;
  size: string;
  description: string;
  url: string;
  fileName: string;
  badge: string | undefined;
  supportsVision: boolean;
  supportsAudio: boolean;
  supportsThinking: boolean;
  supportedBackends: BackendType[];
  maxContextLength: number;
  quantization: string | undefined;
  isEmbedding: boolean;
  isCoder: boolean;
  isInstruct: boolean;
  supportsFunctionCalling: boolean;
  isDraftModel: boolean;
  isASR?: boolean;
  isOCR?: boolean;
  isExperimental?: boolean;
}

export interface ModelState {
  status: ModelStatus;
  progress: number;
  speedMBs?: number;
  bytesDownloaded?: number;
  totalBytes?: number;
  localPath?: string;
  error?: string | null;
}

export const AVAILABLE_MODELS: ModelInfo[] = [
  {
    id: 'qwen2.5-coder-3b-instruct',
    name: 'Qwen2.5-Coder-3B-Instruct',
    tag: 'litert-community',
    size: '3.2 GB',
    description: 'Qwen2.5-Coder-3B-Instruct is a 3B parameter model specialized in code generation, reasoning, and repair. It supports a 32K context window.',
    url: 'https://huggingface.co/litert-community/Qwen2.5-Coder-3B-Instruct/resolve/main/Qwen2.5_Coder_3B_It.litertlm?download=true',
    fileName: 'Qwen2.5_Coder_3B_It.litertlm',
    badge: 'Coder',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: undefined,
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'gemma-4-e2b-it-litert-lm',
    name: 'gemma-4-E2B-it-litert-lm',
    tag: 'litert-community',
    size: '2.6 GB',
    description: 'Gemma 4 E2B is an Effective 2B parameter edge model by Google DeepMind. It is natively multimodal (text, image, audio), supports a 128K context window, and includes a built-in reasoning engine.',
    url: 'https://huggingface.co/litert-community/gemma-4-E2B-it-litert-lm/resolve/main/gemma-4-E2B-it.litertlm?download=true',
    fileName: 'gemma-4-E2B-it-gpu.litertlm',
    badge: 'Multimodal',
    supportsVision: true,
    supportsAudio: true,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 128000,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'gemma-4-26b-a4b-it-litert-lm',
    name: 'gemma-4-26B-A4B-it-litert-lm',
    tag: 'litert-community',
    size: '14.7 GB',
    description: 'Gemma 4 26B A4B is a Mixture-of-Experts model by Google DeepMind with ~25.2B total parameters. It supports multimodal inputs (text, image, video), built-in reasoning, and a 256K context window.',
    url: 'https://huggingface.co/litert-community/gemma-4-26B-A4B-it-litert-lm/resolve/main/gemma-4-26B-A4B-it.litertlm?download=true',
    fileName: 'gemma-4-26B-A4B-it-gpu.litertlm',
    badge: 'Multimodal',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['GPU', 'CPU'],
    maxContextLength: 256000,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'qwen2.5-1.5b-instruct',
    name: 'Qwen2.5-1.5B-Instruct',
    tag: 'litert-community',
    size: '5.8 GB',
    description: 'Qwen2.5-1.5B-Instruct is a 1.5B parameter model supporting 32K context. It features strong instruction following, structured data output, and coding capabilities.',
    url: 'https://huggingface.co/litert-community/Qwen2.5-1.5B-Instruct/resolve/main/Qwen2.5-1.5B-Instruct_multi-prefill-seq_f32_ekv4096.litertlm?download=true',
    fileName: 'Qwen2.5-1.5B-Instruct_multi-prefill-seq_f32_ekv4096.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: 'f32',
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false,
    isExperimental: true
  },
  {
    id: 'gemma-4-e4b-it-litert-lm',
    name: 'gemma-4-E4B-it-litert-lm',
    tag: 'litert-community',
    size: '2.8 GB',
    description: 'Gemma 4 E4B is a 4B parameter multimodal edge model supporting text, image, and audio with a 128K context window. It includes built-in reasoning and agentic workflow support.',
    url: 'https://huggingface.co/litert-community/gemma-4-E4B-it-litert-lm/resolve/main/gemma-4-E4B-it.litertlm?download=true',
    fileName: 'gemma-4-E4B-it-gpu.litertlm',
    badge: 'Multimodal',
    supportsVision: true,
    supportsAudio: true,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 128000,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'gemma-4-12b-it-litert-lm',
    name: 'gemma-4-12B-it-litert-lm',
    tag: 'litert-community',
    size: '5.6 GB',
    description: 'Gemma 4 12B is a Unified multimodal model (text, image, audio) with a 256K context window. It offers strong reasoning, coding, and function calling capabilities.',
    url: 'https://huggingface.co/litert-community/gemma-4-12B-it-litert-lm/resolve/main/gemma-4-12B-it.litertlm?download=true',
    fileName: 'gemma-4-12B-it-gpu.litertlm',
    badge: 'Multimodal',
    supportsVision: true,
    supportsAudio: true,
    supportsThinking: true,
    supportedBackends: ['GPU', 'CPU'],
    maxContextLength: 256000,
    quantization: undefined,
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'fun-asr-nano-2512',
    name: 'Fun-ASR-Nano-2512',
    tag: 'litert-community',
    size: '1.2 GB',
    description: 'Fun-ASR-Nano-2512 is an 800M-parameter end-to-end speech recognition model based on Qwen3-0.6B. Optimized for high-accuracy audio transcription (30s window).',
    url: 'https://huggingface.co/litert-community/Fun-ASR-Nano-2512/resolve/main/Fun-ASR-Nano-2512.litertlm?download=true',
    fileName: 'Fun-ASR-Nano-2512.litertlm',
    badge: 'Audio',
    supportsVision: false,
    supportsAudio: true,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false,
    isASR: true
  },
  {
    id: 'minicpm5-2b',
    name: 'MiniCPM5-2B',
    tag: 'litert-community',
    size: '1.4 GB',
    description: 'MiniCPM5-2B is a highly efficient 2.5B parameter dense model supporting a 128K context window, with strong agentic, coding, and mathematical capabilities.',
    url: 'https://huggingface.co/litert-community/MiniCPM5-2B/resolve/main/MiniCPM5-2B_int4.litertlm?download=true',
    fileName: 'MiniCPM5-2B_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 131072,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'phi-4-mini-instruct',
    name: 'Phi-4-mini-instruct',
    tag: 'litert-community',
    size: '3.6 GB',
    description: 'Phi-4-mini-instruct is a lightweight 3.8B parameter model by Microsoft, supporting a 128K context window. It excels in math, logic, coding, and reasoning tasks.',
    url: 'https://huggingface.co/litert-community/Phi-4-mini-instruct/resolve/main/Phi-4-mini-instruct_multi-prefill-seq_q8_ekv4096.litertlm?download=true',
    fileName: 'Phi-4-mini-instruct_multi-prefill-seq_q8_ekv4096.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['GPU', 'CPU'],
    maxContextLength: 128000,
    quantization: 'q8',
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false,
    isExperimental: true
  },
  {
    id: 'gemma-4-31b-it-litert-lm',
    name: 'gemma-4-31B-it-litert-lm',
    tag: 'litert-community',
    size: '17.9 GB',
    description: 'Gemma 4 31B is a dense 30.7B parameter multimodal model by Google DeepMind. It supports a 256K context window, advanced built-in reasoning, and native function calling.',
    url: 'https://huggingface.co/litert-community/gemma-4-31B-it-litert-lm/resolve/main/gemma-4-31B-it.litertlm?download=true',
    fileName: 'gemma-4-31B-it-gpu.litertlm',
    badge: 'Multimodal',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['GPU', 'CPU'],
    maxContextLength: 256000,
    quantization: undefined,
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'deepseek-r1-distill-qwen-1.5b',
    name: 'DeepSeek-R1-Distill-Qwen-1.5B',
    tag: 'litert-community',
    size: '1.7 GB',
    description: 'DeepSeek-R1-Distill-Qwen-1.5B is a 1.5B parameter distilled reasoning model supporting a 131K context window. It excels in complex logical and mathematical tasks.',
    url: 'https://huggingface.co/litert-community/DeepSeek-R1-Distill-Qwen-1.5B/resolve/main/DeepSeek-R1-Distill-Qwen-1.5B_multi-prefill-seq_q8_ekv4096.litertlm?download=true',
    fileName: 'DeepSeek-R1-Distill-Qwen-1.5B_multi-prefill-seq_q8_ekv4096.litertlm',
    badge: 'Reasoning',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['GPU', 'CPU'],
    maxContextLength: 131072,
    quantization: 'q8',
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false,
    isExperimental: true
  },
  {
    id: 'spark-x2.5-4b',
    name: 'Spark-X2.5-4B',
    tag: 'litert-community',
    size: '2.3 GB',
    description: 'Spark-X2.5-4B is a compact 4B parameter model featuring a hybrid attention architecture that enables a massive 1 Million token context window. It supports agentic workflows.',
    url: 'https://huggingface.co/litert-community/Spark-X2.5-4B/resolve/main/Spark-X2.5-4B_int4.litertlm?download=true',
    fileName: 'Spark-X2.5-4B_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 1000000,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'paddleocr-vl-1.6',
    name: 'PaddleOCR-VL-1.6',
    tag: 'litert-community',
    size: '1.3 GB',
    description: 'PaddleOCR-VL-1.6 is a highly efficient 0.9B parameter vision-language model (VLM) specialized in complex document parsing. It supports a 131K context window.',
    url: 'https://huggingface.co/litert-community/PaddleOCR-VL-1.6/resolve/main/PaddleOCR-VL-1.6.litertlm?download=true',
    fileName: 'PaddleOCR-VL-1.6.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 131072,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false,
    isOCR: true
  },
  {
    id: 'qwen3.5-2b',
    name: 'Qwen3.5-2B',
    tag: 'litert-community',
    size: '2.9 GB',
    description: 'Qwen3.5-2B is a 2B parameter multimodal model (text, image) featuring a hybrid architecture and an massive 262K context window. It also supports a thinking mode.',
    url: 'https://huggingface.co/litert-community/Qwen3.5-2B/resolve/main/Qwen3.5-2B-VL_int8.litertlm?download=true',
    fileName: 'Qwen3.5-2B-VL_int8.litertlm',
    badge: 'Multimodal',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 262144,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen3-0.6b',
    name: 'Qwen3-0.6B',
    tag: 'litert-community',
    size: '0.6 GB',
    description: 'Qwen3-0.6B is a 0.6B parameter ultra-lightweight dense model with a 32K context window. It features a dual-mode architecture (thinking and non-thinking) and supports agentic workflows.',
    url: 'https://huggingface.co/litert-community/Qwen3-0.6B/resolve/main/Qwen3-0.6B.litertlm?download=true',
    fileName: 'Qwen3-0.6B.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'fastvlm-0.5b',
    name: 'FastVLM-0.5B',
    tag: 'litert-community',
    size: '1.1 GB',
    description: 'FastVLM-0.5B is a compact, highly efficient vision-language model by Apple. It features a FastViTHD encoder optimized for on-device, low-latency visual tasks.',
    url: 'https://huggingface.co/litert-community/FastVLM-0.5B/resolve/main/FastVLM-0.5B.litertlm?download=true',
    fileName: 'FastVLM-0.5B.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'functiongemma-mobile-actions_q8_ekv1024.litertlm',
    name: 'functiongemma-mobile-actions_q8_ekv1024.litertlm',
    tag: 'litert-community',
    size: '0.3 GB',
    description: 'FunctionGemma 270M (Mobile Actions) is an on-device model specifically fine-tuned for function calling and API orchestration. It supports a 32K context window.',
    url: 'https://huggingface.co/litert-community/functiongemma-mobile-actions_q8_ekv1024.litertlm/resolve/main/mobile-actions_q8_ekv1024.litertlm?download=true',
    fileName: 'mobile-actions_q8_ekv1024.litertlm',
    badge: 'Agent',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: 'q8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'tinyswallow-1.5b-instruct',
    name: 'TinySwallow-1.5B-Instruct',
    tag: 'litert-community',
    size: '1.5 GB',
    description: 'TinySwallow-1.5B-Instruct is a compact Japanese-English bilingual model by Sakana AI (distilled from Qwen2.5-32B). It supports a 32K context window.',
    url: 'https://huggingface.co/litert-community/TinySwallow-1.5B-Instruct/resolve/main/TinySwallow-1.5B-Instruct.litertlm?download=true',
    fileName: 'TinySwallow-1.5B-Instruct.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'smollm2-360m-instruct',
    name: 'SmolLM2-360M-Instruct',
    tag: 'litert-community',
    size: '0.3 GB',
    description: 'SmolLM2-360M-Instruct is a 362M parameter model optimized for on-device execution. It supports a 2K context window and excels at instruction following and general tasks.',
    url: 'https://huggingface.co/litert-community/SmolLM2-360M-Instruct/resolve/main/SmolLM2_360M_instruct.litertlm?download=true',
    fileName: 'SmolLM2_360M_instruct.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['GPU', 'CPU'],
    maxContextLength: 2048,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen3-4b',
    name: 'Qwen3-4B',
    tag: 'litert-community',
    size: '5.3 GB',
    description: 'Qwen3-4B is a 4B parameter model featuring hybrid reasoning and agentic workflows. It supports a 32K native context window.',
    url: 'https://huggingface.co/litert-community/Qwen3-4B/resolve/main/qwen3_4b_channelwise_int8_float32kv.litertlm?download=true',
    fileName: 'qwen3_4b_channelwise_int8_float32kv.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'qwen3-8b',
    name: 'Qwen3-8B',
    tag: 'litert-community',
    size: '7.7 GB',
    description: 'Qwen3-8B is a dense 8.2B parameter model supporting a 128K context window. It offers hybrid reasoning modes, strong multilingual capabilities, and tool usage.',
    url: 'https://huggingface.co/litert-community/Qwen3-8B/resolve/main/qwen3_8b_channelwise_int8_float32kv.litertlm?download=true',
    fileName: 'qwen3_8b_channelwise_int8_float32kv.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 128000,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'qwen3-4b-instruct-2507',
    name: 'Qwen3-4B-Instruct-2507',
    tag: 'litert-community',
    size: '2.5 GB',
    description: 'Qwen3-4B-Instruct-2507 is an updated 4B parameter non-thinking instruct model. It supports a massive 262K context window and offers strong general-purpose dialogue.',
    url: 'https://huggingface.co/litert-community/Qwen3-4B-Instruct-2507/resolve/main/qwen3_4b_instruct_2507_mixed_int4.litertlm?download=true',
    fileName: 'qwen3_4b_instruct_2507_mixed_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 262144,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'qwen3-asr-0.6b',
    name: 'Qwen3-ASR-0.6B',
    tag: 'litert-community',
    size: '0.9 GB',
    description: 'Qwen3-ASR-0.6B is a compact, high-throughput Automatic Speech Recognition (ASR) model supporting 52 languages. It offers unified streaming and offline inference.',
    url: 'https://huggingface.co/litert-community/Qwen3-ASR-0.6B/resolve/main/qwen3_asr_0.6b_5s_i8.litertlm?download=true',
    fileName: 'qwen3_asr_0.6b_5s_i8.litertlm',
    badge: 'Audio',
    supportsVision: false,
    supportsAudio: true,
    supportsThinking: false,
    supportedBackends: ['CPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false,
    isASR: true
  },
  {
    id: 'qwen3-14b',
    name: 'Qwen3-14B',
    tag: 'litert-community',
    size: '13.9 GB',
    description: 'Qwen3-14B is a 14B parameter hybrid architecture model supporting a native 32K context window (extendable to 131K). It excels in reasoning and agentic tasks.',
    url: 'https://huggingface.co/litert-community/Qwen3-14B/resolve/main/qwen3_14b_channelwise_int8_float32kv.litertlm?download=true',
    fileName: 'qwen3_14b_channelwise_int8_float32kv.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'smollm2-135m-instruct',
    name: 'SmolLM2-135M-Instruct',
    tag: 'litert-community',
    size: '0.1 GB',
    description: 'SmolLM2-135M-Instruct is a highly efficient 135M parameter model. It supports an 8K context window and is optimized for on-device instruction following and summarization.',
    url: 'https://huggingface.co/litert-community/SmolLM2-135M-Instruct/resolve/main/SmolLM2_135M_Instruct.litertlm?download=true',
    fileName: 'SmolLM2_135M_Instruct.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['GPU', 'CPU'],
    maxContextLength: 8192,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'vibethinker-1.5b',
    name: 'VibeThinker-1.5B',
    tag: 'litert-community',
    size: '1.5 GB',
    description: 'VibeThinker-1.5B is a 1.5B parameter dense model optimized for mathematical reasoning and competitive programming. It supports a 131K context window.',
    url: 'https://huggingface.co/litert-community/VibeThinker-1.5B/resolve/main/VibeThinker-1.5B.litertlm?download=true',
    fileName: 'VibeThinker-1.5B.litertlm',
    badge: 'Reasoning',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['GPU', 'CPU'],
    maxContextLength: 131072,
    quantization: undefined,
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen2-1.5b-instruct',
    name: 'Qwen2-1.5B-Instruct',
    tag: 'litert-community',
    size: '1.7 GB',
    description: 'Qwen2-1.5B-Instruct is a 1.5B parameter instruct model supporting a 32K context window. It excels in general chat, tool use, and coding.',
    url: 'https://huggingface.co/litert-community/Qwen2-1.5B-Instruct/resolve/main/Qwen2_1.5B_Instruct.litertlm?download=true',
    fileName: 'Qwen2_1.5B_Instruct.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: undefined,
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'deepseek-r1-distill-qwen-7b',
    name: 'DeepSeek-R1-Distill-Qwen-7B',
    tag: 'litert-community',
    size: '4.2 GB',
    description: 'DeepSeek-R1-Distill-Qwen-7B is a 7B parameter reasoning model supporting a 131K context window. It is highly optimized for complex mathematical problem-solving.',
    url: 'https://huggingface.co/litert-community/DeepSeek-R1-Distill-Qwen-7B/resolve/main/DeepSeek-R1-Distill-Qwen-7B_q4_block32_ekv4096.litertlm?download=true',
    fileName: 'DeepSeek-R1-Distill-Qwen-7B_q4_block32_ekv4096.litertlm',
    badge: 'Reasoning',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 131072,
    quantization: 'q4',
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'qwen2-0.5b-instruct',
    name: 'Qwen2-0.5B-Instruct',
    tag: 'litert-community',
    size: '0.6 GB',
    description: 'Qwen2-0.5B-Instruct is a 0.5B parameter instruct model supporting a 32K context window. It is highly efficient for language understanding and generation.',
    url: 'https://huggingface.co/litert-community/Qwen2-0.5B-Instruct/resolve/main/Qwen2_0.5B_Instruct.litertlm?download=true',
    fileName: 'Qwen2_0.5B_Instruct.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: undefined,
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'qwen3-1.7b',
    name: 'Qwen3-1.7B',
    tag: 'litert-community',
    size: '0.9 GB',
    description: 'Qwen3-1.7B is a 1.7B parameter dense model supporting a 32K context window. It features a dual-mode architecture (thinking and non-thinking).',
    url: 'https://huggingface.co/litert-community/Qwen3-1.7B/resolve/main/Qwen3-1.7B_dynamic_wi4b32_afp32.litertlm?download=true',
    fileName: 'Qwen3-1.7B_dynamic_wi4b32_afp32.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: undefined,
    isEmbedding: false,
    isCoder: true,
    isInstruct: false,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'ministral-3-3b-instruct-2512',
    name: 'Ministral-3-3B-Instruct-2512',
    tag: 'litert-community',
    size: '2.2 GB',
    description: 'Ministral-3-3B-Instruct-2512 is a 3B parameter multimodal model optimized for edge devices. It supports a massive 256K context window and function calling.',
    url: 'https://huggingface.co/litert-community/Ministral-3-3B-Instruct-2512/resolve/main/Ministral-3-3B-Instruct-2512_q4_block32_ekv4096.litertlm?download=true',
    fileName: 'Ministral-3-3B-Instruct-2512_q4_block32_ekv4096.litertlm',
    badge: 'Multimodal',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 256000,
    quantization: 'q4',
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'olmo-2-1b-instruct',
    name: 'OLMo-2-1B-Instruct',
    tag: 'litert-community',
    size: '0.9 GB',
    description: 'OLMo-2-1B-Instruct is a 1B parameter instruct model supporting a 4K context window. It is highly optimized for general chat, reasoning, and instruction following.',
    url: 'https://huggingface.co/litert-community/OLMo-2-1B-Instruct/resolve/main/OLMo-2-1B-Instruct_q4_block32_ekv4096.litertlm?download=true',
    fileName: 'OLMo-2-1B-Instruct_q4_block32_ekv4096.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 4096,
    quantization: 'q4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'fastcontext-1.0-4b-sft',
    name: 'FastContext-1.0-4B-SFT',
    tag: 'litert-community',
    size: '2.5 GB',
    description: 'FastContext-1.0-4B-SFT is a 4B parameter model optimized as a repository-exploration subagent. It efficiently handles large codebases and tools (32K context).',
    url: 'https://huggingface.co/litert-community/FastContext-1.0-4B-SFT/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: 'Agent',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: undefined,
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'smollm3-3b',
    name: 'SmolLM3-3B',
    tag: 'litert-community',
    size: '2.9 GB',
    description: 'SmolLM3-3B is a 3B parameter model supporting a 64K context window (extensible to 128K). It features dual-mode reasoning and high inference efficiency.',
    url: 'https://huggingface.co/litert-community/SmolLM3-3B/resolve/main/SmolLM3-3B.litertlm?download=true',
    fileName: 'SmolLM3-3B.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 64000,
    quantization: undefined,
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'minicpm5-1b',
    name: 'MiniCPM5-1B',
    tag: 'litert-community',
    size: '1.0 GB',
    description: 'MiniCPM5-1B is a 1B parameter dense model optimized for agentic workflows and edge devices. It supports a 131K context window and hybrid reasoning.',
    url: 'https://huggingface.co/litert-community/MiniCPM5-1B/resolve/main/MiniCPM5-1B_dynamic_wi8_afp32.litertlm?download=true',
    fileName: 'MiniCPM5-1B_dynamic_wi8_afp32.litertlm',
    badge: 'Agent',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 131072,
    quantization: undefined,
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'jan-nano',
    name: 'Jan-nano',
    tag: 'litert-community',
    size: '2.3 GB',
    description: 'Jan-Nano is a 4B parameter model designed specifically for deep research tasks. It supports a native 128K context window and seamless MCP server integration.',
    url: 'https://huggingface.co/litert-community/Jan-nano/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: 'Research',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 131072,
    quantization: undefined,
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'internvl3-1b',
    name: 'InternVL3-1B',
    tag: 'litert-community',
    size: '0.7 GB',
    description: 'InternVL3-1B is a 1B parameter vision-language multimodal model. It utilizes variable visual position encoding to efficiently support a 32K context window.',
    url: 'https://huggingface.co/litert-community/InternVL3-1B/resolve/main/InternVL3-1B.litertlm?download=true',
    fileName: 'InternVL3-1B.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'smolvlm2-500m',
    name: 'SmolVLM2-500M',
    tag: 'litert-community',
    size: '0.3 GB',
    description: 'SmolVLM2-500M is a highly compact vision-language model for edge devices. It utilizes pixel-shuffle compression to efficiently handle interleaved inputs within a 2K context.',
    url: 'https://huggingface.co/litert-community/SmolVLM2-500M/resolve/main/SmolVLM2-500M.litertlm?download=true',
    fileName: 'SmolVLM2-500M.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 2048,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'vibethinker-3b',
    name: 'VibeThinker-3B',
    tag: 'litert-community',
    size: '1.9 GB',
    description: 'VibeThinker-3B is a 3B parameter dense reasoning model based on Qwen2.5. It supports a 64K context window and excels at verifiable tasks like math and coding.',
    url: 'https://huggingface.co/litert-community/VibeThinker-3B/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: 'Reasoning',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 64000,
    quantization: undefined,
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen3-4b-thinking-2507',
    name: 'Qwen3-4B-Thinking-2507',
    tag: 'litert-community',
    size: '2.1 GB',
    description: 'Qwen3-4B-Thinking-2507 is an updated 4B parameter model featuring hybrid reasoning capabilities. It supports a 32K context window and agentic workflows.',
    url: 'https://huggingface.co/litert-community/Qwen3-4B-Thinking-2507/resolve/main/Qwen3_4b_thinking_dynamic_wi4b32_afp32.litertlm?download=true',
    fileName: 'Qwen3_4b_thinking_dynamic_wi4b32_afp32.litertlm',
    badge: 'Reasoning',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: undefined,
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'qwen3-0.6b-int4',
    name: 'Qwen3-0.6B-int4',
    tag: 'litert-community',
    size: '0.3 GB',
    description: 'Qwen3-0.6B-int4 is a heavily quantized, highly efficient 0.6B parameter model. It supports up to a 32K context natively, configured here for 1.2K (ekv1280).',
    url: 'https://huggingface.co/litert-community/Qwen3-0.6B-int4/resolve/main/qwen3_0.6b_nothink_q4_block32_ekv1280.litertlm?download=true',
    fileName: 'qwen3_0.6b_nothink_q4_block32_ekv1280.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'CPU'],
    maxContextLength: 1280,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'llava-onevision-0.5b',
    name: 'LLaVA-OneVision-0.5B',
    tag: 'litert-community',
    size: '0.8 GB',
    description: 'LLaVA-OneVision-0.5B is a 0.5B parameter multimodal vision-language model based on Qwen2. It supports a 32K context window and handles high-resolution images.',
    url: 'https://huggingface.co/litert-community/LLaVA-OneVision-0.5B/resolve/main/LLaVA-OneVision-0.5B.litertlm?download=true',
    fileName: 'LLaVA-OneVision-0.5B.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'internvl3-2b',
    name: 'InternVL3-2B',
    tag: 'litert-community',
    size: '1.3 GB',
    description: 'InternVL3-2B is a 2B parameter vision-language model supporting a 32K context window. It excels in document understanding and industrial image analysis.',
    url: 'https://huggingface.co/litert-community/InternVL3-2B/resolve/main/InternVL3-2B.litertlm?download=true',
    fileName: 'InternVL3-2B.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'phi-4-mini-reasoning',
    name: 'Phi-4-mini-reasoning',
    tag: 'litert-community',
    size: '2.6 GB',
    description: 'Phi-4-mini-reasoning is a 3.8B parameter model from Microsoft, optimized for logic-intensive reasoning. It supports a 128K context window.',
    url: 'https://huggingface.co/litert-community/Phi-4-mini-reasoning/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: 'Reasoning',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 128000,
    quantization: undefined,
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'nanbeige4.1-3b',
    name: 'Nanbeige4.1-3B',
    tag: 'litert-community',
    size: '2.2 GB',
    description: 'Nanbeige4.1-3B is a 3B parameter model built for deep-search agentic workflows. It supports a massive 256K context window and extended tool invocations.',
    url: 'https://huggingface.co/litert-community/Nanbeige4.1-3B/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: 'Agent',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 262144,
    quantization: undefined,
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'internvl3_5-2b',
    name: 'InternVL3_5-2B',
    tag: 'litert-community',
    size: '1.5 GB',
    description: 'InternVL3.5-2B is an upgraded 2B parameter multimodal model. It supports a 32K context window and adds thinking mode capabilities for enhanced reasoning.',
    url: 'https://huggingface.co/litert-community/InternVL3_5-2B/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'ovis2.5-2b',
    name: 'Ovis2.5-2B',
    tag: 'litert-community',
    size: '2.0 GB',
    description: 'Ovis2.5-2B is a 2B parameter multimodal model featuring native-resolution visual perception. It supports a 40K context window and an optional thinking mode.',
    url: 'https://huggingface.co/litert-community/Ovis2.5-2B/resolve/main/Ovis2.5-2B.litertlm?download=true',
    fileName: 'Ovis2.5-2B.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 40960,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'internvl3_5-4b',
    name: 'InternVL3_5-4B',
    tag: 'litert-community',
    size: '2.8 GB',
    description: 'InternVL3.5-4B is a 4B parameter multimodal model. It supports a 32K context window and features enhanced reasoning via Cascade RL and thinking mode.',
    url: 'https://huggingface.co/litert-community/InternVL3_5-4B/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'smolvlm2-2.2b',
    name: 'SmolVLM2-2.2B',
    tag: 'litert-community',
    size: '1.4 GB',
    description: 'SmolVLM2-2.2B is a 2.2B parameter multimodal model optimized for video and document understanding. It supports an 8K context window using pixel-shuffle compression.',
    url: 'https://huggingface.co/litert-community/SmolVLM2-2.2B/resolve/main/SmolVLM2-2.2B.litertlm?download=true',
    fileName: 'SmolVLM2-2.2B.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 8192,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'ministral-3-3b-reasoning-2512',
    name: 'Ministral-3-3B-Reasoning-2512',
    tag: 'litert-community',
    size: '2.2 GB',
    description: 'Ministral-3-3B-Reasoning-2512 is a 3B parameter multimodal model tailored for complex reasoning and agentic tasks. It supports a massive 256K context window.',
    url: 'https://huggingface.co/litert-community/Ministral-3-3B-Reasoning-2512/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: 'Reasoning',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 256000,
    quantization: undefined,
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'internvl3_5-1b',
    name: 'InternVL3_5-1B',
    tag: 'litert-community',
    size: '0.8 GB',
    description: 'InternVL3.5-1B is an efficient 1B parameter multimodal model. It supports a 32K context window and offers enhanced reasoning via thinking mode.',
    url: 'https://huggingface.co/litert-community/InternVL3_5-1B/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'polaris-4b-preview',
    name: 'Polaris-4B-Preview',
    tag: 'litert-community',
    size: '2.3 GB',
    description: 'Polaris-4B-Preview is a specialized reasoning model based on Qwen3-4B. It supports up to a 52K context window for complex problem-solving.',
    url: 'https://huggingface.co/litert-community/Polaris-4B-Preview/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: 'Reasoning',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 52000,
    quantization: undefined,
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen2-vl-2b',
    name: 'Qwen2-VL-2B',
    tag: 'litert-community',
    size: '1.7 GB',
    description: 'Qwen2-VL-2B is a 2B parameter vision-language model. It features a 32K context window and uses dynamic resolution for processing images and video.',
    url: 'https://huggingface.co/litert-community/Qwen2-VL-2B/resolve/main/Qwen2-VL-2B.litertlm?download=true',
    fileName: 'Qwen2-VL-2B.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'lfm2.5-1.2b-instruct',
    name: 'LFM2.5-1.2B-Instruct',
    tag: 'litert-community',
    size: '0.7 GB',
    description: 'LFM2.5-1.2B-Instruct is a 1.2B parameter model using a hybrid LIV/GQA architecture. It features a 32K context window and excels at agentic edge tasks.',
    url: 'https://huggingface.co/litert-community/LFM2.5-1.2B-Instruct/resolve/main/LFM2.5-1.2B-Instruct_int4.litertlm?download=true',
    fileName: 'LFM2.5-1.2B-Instruct_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'granite-4.0-350m-litert-lm',
    name: 'granite-4.0-350m-litert-lm',
    tag: 'litert-community',
    size: '0.4 GB',
    description: 'granite-4.0-350m is a highly compact model featuring a hybrid Mamba-2/Transformer architecture. It natively supports up to a 128K context window (configured for 1.2K here).',
    url: 'https://huggingface.co/litert-community/granite-4.0-350m-litert-lm/resolve/main/granite-4.0-350m_q8_ekv1280.litertlm?download=true',
    fileName: 'granite-4.0-350m_q8_ekv1280.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU'],
    maxContextLength: 1280,
    quantization: 'q8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'granite-4.0-h-1b',
    name: 'granite-4.0-h-1b',
    tag: 'litert-community',
    size: '1.6 GB',
    description: 'granite-4.0-h-1b is a 1B parameter hybrid model (Mamba-2 + Transformer) from IBM. It supports a massive 128K context window for long-context tasks.',
    url: 'https://huggingface.co/litert-community/granite-4.0-h-1b/resolve/main/granite-4.0-h-1b_int8.litertlm?download=true',
    fileName: 'granite-4.0-h-1b_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 131072,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'nanbeige4.2-3b',
    name: 'Nanbeige4.2-3B',
    tag: 'litert-community',
    size: '2.4 GB',
    description: 'Nanbeige4.2-3B uses a Looped Transformer architecture to maximize reasoning capacity without adding parameters. It supports a 256K context window.',
    url: 'https://huggingface.co/litert-community/Nanbeige4.2-3B/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: 'Reasoning',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 262144,
    quantization: undefined,
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'minicpm-v-4',
    name: 'MiniCPM-V-4',
    tag: 'litert-community',
    size: '3.9 GB',
    description: 'MiniCPM-V-4 is a highly optimized multimodal model for edge devices. It supports a 262K context window and advanced visual token compression.',
    url: 'https://huggingface.co/litert-community/MiniCPM-V-4/resolve/main/MiniCPM-V-4-int8.litertlm?download=true',
    fileName: 'MiniCPM-V-4-int8.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'CPU'],
    maxContextLength: 262000,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'granite-4.0-h-350m',
    name: 'granite-4.0-h-350m',
    tag: 'litert-community',
    size: '0.7 GB',
    description: 'granite-4.0-h-350m is a highly compact hybrid Mamba-2/Transformer model. It supports up to a 128K context window for efficient long-context processing.',
    url: 'https://huggingface.co/litert-community/granite-4.0-h-350m/resolve/main/granite-4.0-h-350m_fp16.litertlm?download=true',
    fileName: 'granite-4.0-h-350m_fp16.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 131072,
    quantization: 'fp16',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'lfm2.5-1.2b-thinking',
    name: 'LFM2.5-1.2B-Thinking',
    tag: 'litert-community',
    size: '0.7 GB',
    description: 'LFM2.5-1.2B-Thinking utilizes a hybrid LIV/GQA architecture with a 32K context window. It generates chain-of-thought traces for enhanced reasoning and agentic tasks.',
    url: 'https://huggingface.co/litert-community/LFM2.5-1.2B-Thinking/resolve/main/LFM2.5-1.2B-Thinking_int4.litertlm?download=true',
    fileName: 'LFM2.5-1.2B-Thinking_int4.litertlm',
    badge: 'Reasoning',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'mage-vl',
    name: 'Mage-VL',
    tag: 'litert-community',
    size: '2.6 GB',
    description: 'Mage-VL is an efficient vision-language model designed for codec-native streaming. It leverages motion-salient patch selection to achieve a massive 256K context window.',
    url: 'https://huggingface.co/litert-community/Mage-VL/resolve/main/Mage-VL.litertlm?download=true',
    fileName: 'Mage-VL.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 262144,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'lfm2.5-1.2b-jp',
    name: 'LFM2.5-1.2B-JP',
    tag: 'litert-community',
    size: '0.7 GB',
    description: 'LFM2.5-1.2B-JP is a Japanese-focused 1.2B parameter model utilizing a hybrid architecture. It supports a 32K context window for fast on-device inference.',
    url: 'https://huggingface.co/litert-community/LFM2.5-1.2B-JP/resolve/main/LFM2.5-1.2B-JP_int4.litertlm?download=true',
    fileName: 'LFM2.5-1.2B-JP_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen3.5-0.8b',
    name: 'Qwen3.5-0.8B',
    tag: 'litert-community',
    size: '1.2 GB',
    description: 'Qwen3.5-0.8B is an efficient 0.8B parameter multimodal model. It utilizes Gated Delta Networks to natively support an expansive 262K context window.',
    url: 'https://huggingface.co/litert-community/Qwen3.5-0.8B/resolve/main/Qwen3.5-0.8B-VL_int8.litertlm?download=true',
    fileName: 'Qwen3.5-0.8B-VL_int8.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 262144,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'lfm2.5-vl-3b',
    name: 'LFM2.5-VL-3B',
    tag: 'litert-community',
    size: '2.2 GB',
    description: 'LFM2.5-VL-3B is an efficient vision-language model by Liquid AI. Supporting a 32K context window, it excels at UI understanding, visual grounding, and OCR.',
    url: 'https://huggingface.co/litert-community/LFM2.5-VL-3B/resolve/main/LFM2.5-VL-3B_int4.litertlm?download=true',
    fileName: 'LFM2.5-VL-3B_int4.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'lfm2.5-vl-450m',
    name: 'LFM2.5-VL-450M',
    tag: 'litert-community',
    size: '0.4 GB',
    description: 'LFM2.5-VL-450M is a highly compact multimodal vision-language model. It leverages a hybrid architecture to efficiently process a 32K context window on-device.',
    url: 'https://huggingface.co/litert-community/LFM2.5-VL-450M/resolve/main/LFM2.5-VL-450M_int4.litertlm?download=true',
    fileName: 'LFM2.5-VL-450M_int4.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'nemotron-3-embed-1b',
    name: 'Nemotron-3-Embed-1B',
    tag: 'litert-community',
    size: '1.9 GB',
    description: 'Nemotron-3-Embed-1B is a 1.14B parameter text embedding model by NVIDIA. It supports a 32K context window and offers high throughput for RAG workflows.',
    url: 'https://huggingface.co/litert-community/Nemotron-3-Embed-1B/resolve/main/Nemotron-3-Embed-1B_fp16.litertlm?download=true',
    fileName: 'Nemotron-3-Embed-1B_fp16.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: 'fp16',
    isEmbedding: true,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'lfm2.5-embedding-350m',
    name: 'LFM2.5-Embedding-350M',
    tag: 'litert-community',
    size: '0.6 GB',
    description: 'LFM2.5-Embedding-350M is a highly compact embedding model by Liquid AI. It provides 32K context processing with edge-optimized throughput.',
    url: 'https://huggingface.co/litert-community/LFM2.5-Embedding-350M/resolve/main/LFM2.5-Embedding-350M_fp16.litertlm?download=true',
    fileName: 'LFM2.5-Embedding-350M_fp16.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: 'fp16',
    isEmbedding: true,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'shieldstral-1.0-3b',
    name: 'Shieldstral-1.0-3B',
    tag: 'litert-community',
    size: '2.6 GB',
    description: 'Shieldstral-1.0-3B is a policy-adaptive multimodal safety classifier by Mistral AI. It supports a 32K context window and evaluates moderation rules dynamically.',
    url: 'https://huggingface.co/litert-community/Shieldstral-1.0-3B/resolve/main/Shieldstral-1.0-3B-vision_int4.litertlm?download=true',
    fileName: 'Shieldstral-1.0-3B-vision_int4.litertlm',
    badge: 'Security',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'lfm2.5-vl-1.6b',
    name: 'LFM2.5-VL-1.6B',
    tag: 'litert-community',
    size: '1.2 GB',
    description: 'LFM2.5-VL-1.6B is a compact, highly efficient vision-language model. It features a 32K context window and excels at on-device screen and UI understanding.',
    url: 'https://huggingface.co/litert-community/LFM2.5-VL-1.6B/resolve/main/LFM2.5-VL-1.6B_int4.litertlm?download=true',
    fileName: 'LFM2.5-VL-1.6B_int4.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'lfm2.5-2.6b',
    name: 'LFM2.5-2.6B',
    tag: 'litert-community',
    size: '1.6 GB',
    description: 'LFM2.5-2.6B is a 2.6B parameter model utilizing a hybrid architecture for high edge throughput. It provides a robust 32K context window natively.',
    url: 'https://huggingface.co/litert-community/LFM2.5-2.6B/resolve/main/LFM2.5-2.6B_int4.litertlm?download=true',
    fileName: 'LFM2.5-2.6B_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'falcon-h1-0.5b-instruct',
    name: 'Falcon-H1-0.5B-Instruct',
    tag: 'litert-community',
    size: '0.6 GB',
    description: 'Falcon-H1-0.5B-Instruct is a 0.5B parameter hybrid model (Transformer + Mamba-2). It supports a massive 256K context window for long-range reasoning.',
    url: 'https://huggingface.co/litert-community/Falcon-H1-0.5B-Instruct/resolve/main/Falcon-H1-0.5B-Instruct_int8.litertlm?download=true',
    fileName: 'Falcon-H1-0.5B-Instruct_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 262144,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'nemotron-h-4b-instruct-128k',
    name: 'Nemotron-H-4B-Instruct-128K',
    tag: 'litert-community',
    size: '4.5 GB',
    description: 'Nemotron-H-4B-Instruct-128K is a 4B parameter hybrid model (Mamba-2 + MLP) by NVIDIA. It supports a 128K context window for long-sequence multi-turn chat.',
    url: 'https://huggingface.co/litert-community/Nemotron-H-4B-Instruct-128K/resolve/main/Nemotron-H-4B-Instruct-128K_int8.litertlm?download=true',
    fileName: 'Nemotron-H-4B-Instruct-128K_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 131072,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'granite-embedding-311m-multilingual-r2',
    name: 'granite-embedding-311m-multilingual-r2',
    tag: 'litert-community',
    size: '0.4 GB',
    description: 'granite-embedding-311m-multilingual-r2 is an embedding model by IBM. It supports a 32K context window and handles over 200 languages for robust RAG.',
    url: 'https://huggingface.co/litert-community/granite-embedding-311m-multilingual-r2/resolve/main/granite-embedding-311m-r2_fp16.litertlm?download=true',
    fileName: 'granite-embedding-311m-r2_fp16.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: 'fp16',
    isEmbedding: true,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'north-micro-vision-instruct',
    name: 'North-Micro-Vision-Instruct',
    tag: 'litert-community',
    size: '2.0 GB',
    description: 'North-Micro-Vision-Instruct is a 2.4B parameter vision-language model by Cohere. It supports a 128K context for text and an 8K validated range for multimodal inputs.',
    url: 'https://huggingface.co/litert-community/North-Micro-Vision-Instruct/resolve/main/North-Micro-Vision-Instruct_int4.litertlm?download=true',
    fileName: 'North-Micro-Vision-Instruct_int4.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 131072,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'falcon-h1-1.5b-deep-instruct',
    name: 'Falcon-H1-1.5B-Deep-Instruct',
    tag: 'litert-community',
    size: '1.7 GB',
    description: 'Falcon-H1-1.5B-Deep-Instruct uses a deeper, narrower hybrid architecture (Mamba-2 + Transformer). It natively supports a 256K context window for complex reasoning.',
    url: 'https://huggingface.co/litert-community/Falcon-H1-1.5B-Deep-Instruct/resolve/main/Falcon-H1-1.5B-Deep-Instruct_int8.litertlm?download=true',
    fileName: 'Falcon-H1-1.5B-Deep-Instruct_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 262144,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'codegemma-7b-it-int4-litertlm',
    name: 'codegemma-7b-it-int4-litertlm',
    tag: 'litert-community',
    size: '4.4 GB',
    description: 'codegemma-7b-it-int4 is a 7B parameter instruction-tuned model by Google optimized for coding tasks, completion, and chat. It supports an 8K context window.',
    url: 'https://huggingface.co/litert-community/codegemma-7b-it-int4-litertlm/resolve/main/codegemma-7b-it-int4-litertlm.litertlm?download=true',
    fileName: 'codegemma-7b-it-int4-litertlm.litertlm',
    badge: 'Code',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU'],
    maxContextLength: 8192,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen2.5-coder-1.5b-instruct',
    name: 'Qwen2.5-Coder-1.5B-Instruct',
    tag: 'litert-community',
    size: '1.0 GB',
    description: 'Qwen2.5-Coder-1.5B-Instruct is specialized for code generation, reasoning, and fixes. It features a 32K context window and strong instruction-following capabilities.',
    url: 'https://huggingface.co/litert-community/Qwen2.5-Coder-1.5B-Instruct/resolve/main/Qwen2.5-Coder-1.5B-Instruct_int4.litertlm?download=true',
    fileName: 'Qwen2.5-Coder-1.5B-Instruct_int4.litertlm',
    badge: 'Code',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'falcon-h1-1.5b-instruct',
    name: 'Falcon-H1-1.5B-Instruct',
    tag: 'litert-community',
    size: '1.6 GB',
    description: 'Falcon-H1-1.5B-Instruct leverages a hybrid architecture (Mamba-2 + Transformer) for high efficiency. It supports up to a 256K context window.',
    url: 'https://huggingface.co/litert-community/Falcon-H1-1.5B-Instruct/resolve/main/Falcon-H1-1.5B-Instruct_int8.litertlm?download=true',
    fileName: 'Falcon-H1-1.5B-Instruct_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 262144,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'zamba2-1.2b-instruct',
    name: 'Zamba2-1.2B-instruct',
    tag: 'litert-community',
    size: '1.3 GB',
    description: 'Zamba2-1.2B-instruct is a highly efficient hybrid model (Mamba2 + Transformer). It supports a 4K context window and offers strong instruction-following capabilities.',
    url: 'https://huggingface.co/litert-community/Zamba2-1.2B-instruct/resolve/main/Zamba2-1.2B-instruct_int8.litertlm?download=true',
    fileName: 'Zamba2-1.2B-instruct_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 4096,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'falcon-h1-3b-instruct',
    name: 'Falcon-H1-3B-Instruct',
    tag: 'litert-community',
    size: '3.2 GB',
    description: 'Falcon-H1-3B-Instruct is a 3B parameter hybrid model designed for robust on-device inference. It features a massive 256K context window and handles 18+ languages natively.',
    url: 'https://huggingface.co/litert-community/Falcon-H1-3B-Instruct/resolve/main/Falcon-H1-3B-Instruct_int8.litertlm?download=true',
    fileName: 'Falcon-H1-3B-Instruct_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 262144,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'granite-4.1-3b',
    name: 'granite-4.1-3b',
    tag: 'litert-community',
    size: '2.0 GB',
    description: 'granite-4.1-3b is an efficient dense decoder-only model by IBM. It natively supports up to a 128K context window for long-form enterprise tasks.',
    url: 'https://huggingface.co/litert-community/granite-4.1-3b/resolve/main/granite-4.1-3b_int4.litertlm?download=true',
    fileName: 'granite-4.1-3b_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 131072,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'qwen3.5-4b',
    name: 'Qwen3.5-4B',
    tag: 'litert-community',
    size: '4.1 GB',
    description: 'Qwen3.5-4B is a highly capable hybrid multimodal model. Utilizing Gated Delta Networks, it efficiently processes an expansive 262K context window.',
    url: 'https://huggingface.co/litert-community/Qwen3.5-4B/resolve/main/Qwen3.5-4B_int8.litertlm?download=true',
    fileName: 'Qwen3.5-4B_int8.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 262144,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'zamba2-2.7b-instruct',
    name: 'Zamba2-2.7B-instruct',
    tag: 'litert-community',
    size: '2.6 GB',
    description: 'Zamba2-2.7B-instruct is an advanced hybrid SLM (Mamba2 + Transformer). It offers a 4K context window with exceptionally low inference latency.',
    url: 'https://huggingface.co/litert-community/Zamba2-2.7B-instruct/resolve/main/Zamba2-2.7B-instruct_int8.litertlm?download=true',
    fileName: 'Zamba2-2.7B-instruct_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 4096,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'smollm2-1.7b-instruct',
    name: 'SmolLM2-1.7B-Instruct',
    tag: 'litert-community',
    size: '1.6 GB',
    description: 'SmolLM2-1.7B-Instruct is a compact and highly performant model based on the Llama-2 architecture. It supports an 8K context window for fast local inference.',
    url: 'https://huggingface.co/litert-community/SmolLM2-1.7B-Instruct/resolve/main/SmolLM2-1_7B-Instruct_dynamic_wi8_afp32.litertlm?download=true',
    fileName: 'SmolLM2-1_7B-Instruct_dynamic_wi8_afp32.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 8192,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'hy-mt2-1.8b',
    name: 'Hy-MT2-1.8B',
    tag: 'litert-community',
    size: '1.7 GB',
    description: 'Hy-MT2-1.8B is a specialized, lightweight multilingual translation model. It supports an 8K context window and handles complex translation-specific workflows natively.',
    url: 'https://huggingface.co/litert-community/Hy-MT2-1.8B/resolve/main/Hy-MT2-1.8B_int8.litertlm?download=true',
    fileName: 'Hy-MT2-1.8B_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['GPU', 'CPU'],
    maxContextLength: 8192,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'falcon-h1-tiny-r-0.6b',
    name: 'Falcon-H1-Tiny-R-0.6B',
    tag: 'litert-community',
    size: '0.8 GB',
    description: 'Falcon-H1-Tiny-R-0.6B is a reasoning-focused hybrid model optimized for local inference. It supports an 8K context window for efficient mathematical and logic tasks.',
    url: 'https://huggingface.co/litert-community/Falcon-H1-Tiny-R-0.6B/resolve/main/Falcon-H1-Tiny-R-0.6B_int8.litertlm?download=true',
    fileName: 'Falcon-H1-Tiny-R-0.6B_int8.litertlm',
    badge: 'Reasoning',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 8192,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'vibevoice-asr-bitnet',
    name: 'VibeVoice-ASR-BitNet',
    tag: 'litert-community',
    size: '1.8 GB',
    description: 'VibeVoice-ASR-BitNet is an efficient ASR model optimized for edge devices without GPUs. Utilizing PoSE, it can process up to 60-minute long-form audio natively.',
    url: 'https://huggingface.co/litert-community/VibeVoice-ASR-BitNet/resolve/main/VibeVoice-ASR-BitNet.litertlm?download=true',
    fileName: 'VibeVoice-ASR-BitNet.litertlm',
    badge: 'Audio',
    supportsVision: false,
    supportsAudio: true,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false,
    isASR: true
  },
  {
    id: 'sarashina2.2-0.5b-instruct-v0.1',
    name: 'sarashina2.2-0.5b-instruct-v0.1',
    tag: 'litert-community',
    size: '0.5 GB',
    description: 'sarashina2.2-0.5b-instruct is a highly compact Japanese-centric language model. It supports an 8K context window for optimized local inference.',
    url: 'https://huggingface.co/litert-community/sarashina2.2-0.5b-instruct-v0.1/resolve/main/sarashina2.2-0.5b-instruct-v0.1_int4.litertlm?download=true',
    fileName: 'sarashina2.2-0.5b-instruct-v0.1_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 8192,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'sarashina2.2-1b-instruct-v0.1',
    name: 'sarashina2.2-1b-instruct-v0.1',
    tag: 'litert-community',
    size: '0.8 GB',
    description: 'sarashina2.2-1b-instruct is a 1B parameter Japanese-focused language model. It supports an 8K context window for fast on-device text generation.',
    url: 'https://huggingface.co/litert-community/sarashina2.2-1b-instruct-v0.1/resolve/main/sarashina2.2-1b-instruct-v0.1_int4.litertlm?download=true',
    fileName: 'sarashina2.2-1b-instruct-v0.1_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 8192,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'nemotron-3-nano-4b',
    name: 'Nemotron-3-Nano-4B',
    tag: 'litert-community',
    size: '3.8 GB',
    description: 'Nemotron-3-Nano-4B is a highly capable hybrid Mamba-Transformer model by NVIDIA. It supports an expansive 262K context window for long-sequence reasoning.',
    url: 'https://huggingface.co/litert-community/Nemotron-3-Nano-4B/resolve/main/Nemotron-3-Nano-4B_int8.litertlm?download=true',
    fileName: 'Nemotron-3-Nano-4B_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['GPU', 'CPU'],
    maxContextLength: 262144,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'granite-docling-258m',
    name: 'granite-docling-258M',
    tag: 'litert-community',
    size: '0.3 GB',
    description: 'granite-docling-258M is an ultra-compact vision-language model optimized for structural document parsing. It outputs DocTags for hierarchical RAG formatting (8K context).',
    url: 'https://huggingface.co/litert-community/granite-docling-258M/resolve/main/granite-docling-258M.litertlm?download=true',
    fileName: 'granite-docling-258M.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 8192,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'granite-4.2-3b',
    name: 'granite-4.2-3b',
    tag: 'litert-community',
    size: '2.0 GB',
    description: 'granite-4.2-3b is an advanced dense decoder-only model by IBM. It natively supports up to a 128K context window for long-form enterprise instructions.',
    url: 'https://huggingface.co/litert-community/granite-4.2-3b/resolve/main/granite-4.2-3b_int4.litertlm?download=true',
    fileName: 'granite-4.2-3b_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 131072,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'lfm2.5-230m',
    name: 'LFM2.5-230M',
    tag: 'litert-community',
    size: '0.2 GB',
    description: 'LFM2.5-230M is an ultra-compact language model by Liquid AI. It features a 32K context window, highly optimized for extremely low-latency edge inference.',
    url: 'https://huggingface.co/litert-community/LFM2.5-230M/resolve/main/LFM2.5-230M_int4.litertlm?download=true',
    fileName: 'LFM2.5-230M_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'agents-a1-4b',
    name: 'Agents-A1-4B',
    tag: 'litert-community',
    size: '4.1 GB',
    description: 'Agents-A1-4B is an agent-specialized 4B parameter model with a 262K context window. It excels at long-horizon search and multi-step tool execution.',
    url: 'https://huggingface.co/litert-community/Agents-A1-4B/resolve/main/Agents-A1-4B_int8.litertlm?download=true',
    fileName: 'Agents-A1-4B_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['GPU', 'CPU'],
    maxContextLength: 262144,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'ternary-bonsai-1.7b',
    name: 'Ternary-Bonsai-1.7B',
    tag: 'litert-community',
    size: '0.7 GB',
    description: 'Ternary-Bonsai-1.7B leverages ternary weight quantization for extreme efficiency. It supports up to a 32K context window while maintaining strong local inference.',
    url: 'https://huggingface.co/litert-community/Ternary-Bonsai-1.7B/resolve/main/bonsai-1.7b-int2pc-32k-crashfix.litertlm?download=true',
    fileName: 'bonsai-1.7b-int2pc-32k-crashfix.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: 'int2',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'vibevoice-asr-streaming-1.5b',
    name: 'VibeVoice-ASR-Streaming-1.5B',
    tag: 'litert-community',
    size: '1.9 GB',
    description: 'VibeVoice-ASR-Streaming-1.5B is optimized for real-time speech recognition. It streams audio locally with extremely low latency and an efficient acoustic tokenizer.',
    url: 'https://huggingface.co/litert-community/VibeVoice-ASR-Streaming-1.5B/resolve/main/VibeVoice-ASR-Streaming-1.5B.litertlm?download=true',
    fileName: 'VibeVoice-ASR-Streaming-1.5B.litertlm',
    badge: 'Audio',
    supportsVision: false,
    supportsAudio: true,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false,
    isASR: true
  },
  {
    id: 'embeddinggemma-300m-tensor-g4-npu',
    name: 'EmbeddingGemma-300M-Tensor-G4-NPU',
    tag: 'litert-community',
    size: '0.2 GB',
    description: 'EmbeddingGemma-300M-Tensor-G4-NPU is a highly optimized embedding model by Google. It leverages the NPU for ultra-low latency semantic search tasks.',
    url: 'https://huggingface.co/litert-community/EmbeddingGemma-300M-Tensor-G4-NPU/resolve/main/EmbeddingGemma-300M_seq256_Google_Tensor_G4.litertlm?download=true',
    fileName: 'EmbeddingGemma-300M_seq256_Google_Tensor_G4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 256,
    quantization: undefined,
    isEmbedding: true,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'decider-0.8b-litert',
    name: 'decider-0.8b-LiteRT',
    tag: 'litert-community',
    size: '1.5 GB',
    description: 'decider-0.8b-LiteRT is an ultra-compact language model focused on rapid, low-latency decision making and simple instruction execution.',
    url: 'https://huggingface.co/litert-community/decider-0.8b-LiteRT/resolve/main/decider-0.8b_fp16.litertlm?download=true',
    fileName: 'decider-0.8b_fp16.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 8192,
    quantization: 'fp16',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'phi-3-mini-4k-instruct',
    name: 'Phi-3-mini-4k-instruct',
    tag: 'litert-community',
    size: '3.6 GB',
    description: 'Phi-3-mini-4k-instruct is a highly capable 3.8B parameter model by Microsoft. It delivers excellent reasoning and coding performance within a 4K context window.',
    url: 'https://huggingface.co/litert-community/Phi-3-mini-4k-instruct/resolve/main/phi3_mini_4k_instruct_int8.litertlm?download=true',
    fileName: 'phi3_mini_4k_instruct_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 4096,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: false
  },
  {
    id: 'spark-x2.5-1.7b',
    name: 'Spark-X2.5-1.7B',
    tag: 'litert-community',
    size: '1.2 GB',
    description: 'Spark-X2.5-1.7B uses a hybrid attention architecture to efficiently support an extreme 1M token context window for massive document processing natively.',
    url: 'https://huggingface.co/litert-community/Spark-X2.5-1.7B/resolve/main/Spark-X2.5-1.7B_int4.litertlm?download=true',
    fileName: 'Spark-X2.5-1.7B_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 1000000,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'gemma3-1b-it-tensor-npu',
    name: 'Gemma3-1B-IT-Tensor-NPU',
    tag: 'litert-community',
    size: '0.8 GB',
    description: 'Gemma3-1B-IT-Tensor-NPU is optimized to run on device neural processing units natively. It supports a 4K context window for fast edge instruction following.',
    url: 'https://huggingface.co/litert-community/Gemma3-1B-IT-Tensor-NPU/resolve/main/Gemma3-1B-IT_int4hadamard_aot_ekv4096_G3.litertlm?download=true',
    fileName: 'Gemma3-1B-IT_int4hadamard_aot_ekv4096_G3.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU'],
    maxContextLength: 4096,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: '1bit-bonsai-1.7b-poc',
    name: '1Bit-Bonsai-1.7B-PoC',
    tag: 'litert-community',
    size: '0.5 GB',
    description: '1Bit-Bonsai-1.7B-PoC is a proof-of-concept utilizing 1-bit quantization for minimal memory usage while preserving local inference capabilities.',
    url: 'https://huggingface.co/litert-community/1Bit-Bonsai-1.7B-PoC/resolve/main/bonsai-1.7b-int1-REAL.litertlm?download=true',
    fileName: 'bonsai-1.7b-int1-REAL.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: 'int1',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'ternary-bonsai-8b',
    name: 'Ternary-Bonsai-8B',
    tag: 'litert-community',
    size: '2.4 GB',
    description: 'Ternary-Bonsai-8B is a larger 8B parameter model employing ternary (2-bit) quantization. It efficiently provides a 32K context window on edge hardware.',
    url: 'https://huggingface.co/litert-community/Ternary-Bonsai-8B/resolve/main/bonsai-8b-int2pc-32k-crashfix.litertlm?download=true',
    fileName: 'bonsai-8b-int2pc-32k-crashfix.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU', 'GPU', 'CPU'],
    maxContextLength: 32768,
    quantization: 'int2',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
];

interface LLMState {
  selectedModelId: string;
  loadedModelId: string | null;
  preferredBackend: BackendType;
  activeBackend: string | null;
  modelStatuses: Record<string, ModelState>;
  isGenerating: boolean;
}

const initialModelStatuses: Record<string, ModelState> = AVAILABLE_MODELS.reduce(
  (acc, model) => {
    acc[model.id] = {
      status: 'not_downloaded',
      progress: 0,
      speedMBs: 0,
      bytesDownloaded: 0,
      totalBytes: 0,
      error: null,
    };
    return acc;
  },
  {} as Record<string, ModelState>
);

const initialState: LLMState = {
  selectedModelId: 'gemma-4-e2b',
  loadedModelId: null,
  preferredBackend: 'AUTO',
  activeBackend: null,
  modelStatuses: initialModelStatuses,
  isGenerating: false,
};

const llmSlice = createSlice({
  name: 'llm',
  initialState,
  reducers: {
    setSelectedModel: (state, action: PayloadAction<string>) => {
      state.selectedModelId = action.payload;
    },
    setPreferredBackend: (state, action: PayloadAction<BackendType>) => {
      state.preferredBackend = action.payload;
    },
    setActiveBackend: (state, action: PayloadAction<string | null>) => {
      state.activeBackend = action.payload;
    },
    startDownload: (state, action: PayloadAction<string>) => {
      const modelId = action.payload;
      state.modelStatuses[modelId] = {
        status: 'downloading',
        progress: 0,
        speedMBs: 0,
        bytesDownloaded: 0,
        totalBytes: 0,
        error: null,
      };
    },
    setDownloadProgress: (
      state,
      action: PayloadAction<{
        modelId: string;
        progress: number;
        speedMBs?: number;
        bytesDownloaded?: number;
        totalBytes?: number;
      }>
    ) => {
      const { modelId, progress, speedMBs, bytesDownloaded, totalBytes } =
        action.payload;
      if (state.modelStatuses[modelId]) {
        state.modelStatuses[modelId].status = 'downloading';
        state.modelStatuses[modelId].progress = progress;
        if (speedMBs !== undefined) state.modelStatuses[modelId].speedMBs = speedMBs;
        if (bytesDownloaded !== undefined)
          state.modelStatuses[modelId].bytesDownloaded = bytesDownloaded;
        if (totalBytes !== undefined)
          state.modelStatuses[modelId].totalBytes = totalBytes;
      }
    },
    setDownloaded: (
      state,
      action: PayloadAction<{ modelId: string; localPath?: string }>
    ) => {
      const { modelId, localPath } = action.payload;
      state.modelStatuses[modelId] = {
        status: 'downloaded',
        progress: 100,
        localPath: localPath || state.modelStatuses[modelId]?.localPath,
        error: null,
      };
    },
    setDownloadError: (
      state,
      action: PayloadAction<{ modelId: string; error: string }>
    ) => {
      const { modelId, error } = action.payload;
      if (state.modelStatuses[modelId]) {
        state.modelStatuses[modelId].status = 'not_downloaded';
        state.modelStatuses[modelId].progress = 0;
        state.modelStatuses[modelId].error = error;
      }
    },
    syncModelStatus: (
      state,
      action: PayloadAction<{
        modelId: string;
        isDownloaded: boolean;
        localPath?: string;
      }>
    ) => {
      const { modelId, isDownloaded, localPath } = action.payload;
      if (state.modelStatuses[modelId]) {
        if (isDownloaded) {
          state.modelStatuses[modelId].status =
            state.loadedModelId === modelId ? 'loaded' : 'downloaded';
          state.modelStatuses[modelId].progress = 100;
          state.modelStatuses[modelId].localPath = localPath;
        } else if (state.modelStatuses[modelId].status !== 'downloading') {
          state.modelStatuses[modelId].status = 'not_downloaded';
          state.modelStatuses[modelId].progress = 0;
        }
      }
    },
    startLoadingModel: (state, action: PayloadAction<string>) => {
      const modelId = action.payload;
      if (state.modelStatuses[modelId]) {
        state.modelStatuses[modelId].status = 'loading';
        state.modelStatuses[modelId].error = null;
      }
    },
    setModelLoadFailed: (
      state,
      action: PayloadAction<{ modelId: string; error: string }>
    ) => {
      // A load attempt only starts once a model is downloaded, so on failure
      // we revert its status back to 'downloaded' (never stuck on 'loading').
      const { modelId, error } = action.payload;
      if (state.modelStatuses[modelId]) {
        state.modelStatuses[modelId].status = 'downloaded';
        state.modelStatuses[modelId].error = error;
      }
      if (state.loadedModelId === modelId) {
        state.loadedModelId = null;
        state.activeBackend = null;
      }
    },
    setLoadedModel: (
      state,
      action: PayloadAction<{ modelId: string; backend?: string }>
    ) => {
      const { modelId, backend } = action.payload;
      if (state.loadedModelId && state.loadedModelId !== modelId) {
        if (state.modelStatuses[state.loadedModelId]?.status === 'loaded') {
          state.modelStatuses[state.loadedModelId].status = 'downloaded';
        }
      }
      state.selectedModelId = modelId;
      state.loadedModelId = modelId;
      if (backend) {
        state.activeBackend = backend;
      }
      if (state.modelStatuses[modelId]) {
        state.modelStatuses[modelId].status = 'loaded';
      }
    },
    deleteModel: (state, action: PayloadAction<string>) => {
      const modelId = action.payload;
      state.modelStatuses[modelId] = {
        status: 'not_downloaded',
        progress: 0,
        speedMBs: 0,
        bytesDownloaded: 0,
        totalBytes: 0,
        localPath: undefined,
        error: null,
      };
      if (state.loadedModelId === modelId) {
        state.loadedModelId = null;
        state.activeBackend = null;
      }
    },
    unloadModel: (state) => {
      if (state.loadedModelId && state.modelStatuses[state.loadedModelId]) {
        state.modelStatuses[state.loadedModelId].status = 'downloaded';
      }
      state.loadedModelId = null;
      state.activeBackend = null;
    },
    setIsGenerating: (state, action: PayloadAction<boolean>) => {
      state.isGenerating = action.payload;
    },
  },
});

export const {
  setSelectedModel,
  setPreferredBackend,
  setActiveBackend,
  startDownload,
  setDownloadProgress,
  setDownloaded,
  setDownloadError,
  syncModelStatus,
  startLoadingModel,
  setModelLoadFailed,
  setLoadedModel,
  deleteModel,
  unloadModel,
  setIsGenerating,
} = llmSlice.actions;

export default llmSlice.reducer;
