import { createSlice, PayloadAction } from '@reduxjs/toolkit';

export type ModelStatus =
  | 'not_downloaded'
  | 'downloading'
  | 'downloaded'
  | 'loading'
  | 'loaded';

export type BackendType = 'AUTO' | 'NPU' | 'GPU' | 'CPU';

export interface ModelInfo {
  id: string;
  name: string;
  tag: string;
  size: string;
  description: string;
  url: string;
  fileName: string;
  badge: string | undefined;
  supportsVision: boolean;
  supportsAudio: boolean;
  supportsThinking: boolean;
  supportedBackends: BackendType[];
  maxContextLength: number;
  quantization: string | undefined;
  isEmbedding: boolean;
  isCoder: boolean;
  isInstruct: boolean;
  supportsFunctionCalling: boolean;
  isDraftModel: boolean;
}

export interface ModelState {
  status: ModelStatus;
  progress: number;
  speedMBs?: number;
  bytesDownloaded?: number;
  totalBytes?: number;
  localPath?: string;
  error?: string | null;
}

export const AVAILABLE_MODELS: ModelInfo[] = [
  {
    id: 'qwen2.5-coder-3b-instruct',
    name: 'Qwen2.5-Coder-3B-Instruct',
    tag: 'litert-community',
    size: '3.2 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Qwen2.5-Coder-3B-Instruct/resolve/main/Qwen2.5_Coder_3B_It.litertlm?download=true',
    fileName: 'Qwen2.5_Coder_3B_It.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'gemma-4-e2b-it-litert-lm',
    name: 'gemma-4-E2B-it-litert-lm',
    tag: 'litert-community',
    size: '1.9 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/gemma-4-E2B-it-litert-lm/resolve/main/gemma-4-E2B-it-gpu.litertlm?download=true',
    fileName: 'gemma-4-E2B-it-gpu.litertlm',
    badge: 'Multimodal',
    supportsVision: true,
    supportsAudio: true,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'gemma-4-26b-a4b-it-litert-lm',
    name: 'gemma-4-26B-A4B-it-litert-lm',
    tag: 'litert-community',
    size: '14.7 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/gemma-4-26B-A4B-it-litert-lm/resolve/main/gemma-4-26B-A4B-it-gpu.litertlm?download=true',
    fileName: 'gemma-4-26B-A4B-it-gpu.litertlm',
    badge: 'Multimodal',
    supportsVision: true,
    supportsAudio: true,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen2.5-1.5b-instruct',
    name: 'Qwen2.5-1.5B-Instruct',
    tag: 'litert-community',
    size: '5.8 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Qwen2.5-1.5B-Instruct/resolve/main/Qwen2.5-1.5B-Instruct_multi-prefill-seq_f32_ekv4096.litertlm?download=true',
    fileName: 'Qwen2.5-1.5B-Instruct_multi-prefill-seq_f32_ekv4096.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 4096,
    quantization: 'f32',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'gemma-4-e4b-it-litert-lm',
    name: 'gemma-4-E4B-it-litert-lm',
    tag: 'litert-community',
    size: '2.8 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/gemma-4-E4B-it-litert-lm/resolve/main/gemma-4-E4B-it-gpu.litertlm?download=true',
    fileName: 'gemma-4-E4B-it-gpu.litertlm',
    badge: 'Multimodal',
    supportsVision: true,
    supportsAudio: true,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'gemma-4-12b-it-litert-lm',
    name: 'gemma-4-12B-it-litert-lm',
    tag: 'litert-community',
    size: '5.6 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/gemma-4-12B-it-litert-lm/resolve/main/gemma-4-12B-it-gpu.litertlm?download=true',
    fileName: 'gemma-4-12B-it-gpu.litertlm',
    badge: 'Multimodal',
    supportsVision: true,
    supportsAudio: true,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'fun-asr-nano-2512',
    name: 'Fun-ASR-Nano-2512',
    tag: 'litert-community',
    size: '1.2 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Fun-ASR-Nano-2512/resolve/main/Fun-ASR-Nano-2512.litertlm?download=true',
    fileName: 'Fun-ASR-Nano-2512.litertlm',
    badge: 'Audio',
    supportsVision: false,
    supportsAudio: true,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: true
  },
  {
    id: 'minicpm5-2b',
    name: 'MiniCPM5-2B',
    tag: 'litert-community',
    size: '1.4 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/MiniCPM5-2B/resolve/main/MiniCPM5-2B_int4.litertlm?download=true',
    fileName: 'MiniCPM5-2B_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'phi-4-mini-instruct',
    name: 'Phi-4-mini-instruct',
    tag: 'litert-community',
    size: '3.6 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Phi-4-mini-instruct/resolve/main/Phi-4-mini-instruct_multi-prefill-seq_q8_ekv4096.litertlm?download=true',
    fileName: 'Phi-4-mini-instruct_multi-prefill-seq_q8_ekv4096.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 4096,
    quantization: 'q8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'gemma-4-31b-it-litert-lm',
    name: 'gemma-4-31B-it-litert-lm',
    tag: 'litert-community',
    size: '17.9 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/gemma-4-31B-it-litert-lm/resolve/main/gemma-4-31B-it-gpu.litertlm?download=true',
    fileName: 'gemma-4-31B-it-gpu.litertlm',
    badge: 'Multimodal',
    supportsVision: true,
    supportsAudio: true,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'deepseek-r1-distill-qwen-1.5b',
    name: 'DeepSeek-R1-Distill-Qwen-1.5B',
    tag: 'litert-community',
    size: '1.7 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/DeepSeek-R1-Distill-Qwen-1.5B/resolve/main/DeepSeek-R1-Distill-Qwen-1.5B_multi-prefill-seq_q8_ekv4096.litertlm?download=true',
    fileName: 'DeepSeek-R1-Distill-Qwen-1.5B_multi-prefill-seq_q8_ekv4096.litertlm',
    badge: 'Reasoning',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 4096,
    quantization: 'q8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'spark-x2.5-4b',
    name: 'Spark-X2.5-4B',
    tag: 'litert-community',
    size: '2.3 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Spark-X2.5-4B/resolve/main/Spark-X2.5-4B_int4.litertlm?download=true',
    fileName: 'Spark-X2.5-4B_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'paddleocr-vl-1.6',
    name: 'PaddleOCR-VL-1.6',
    tag: 'litert-community',
    size: '1.3 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/PaddleOCR-VL-1.6/resolve/main/PaddleOCR-VL-1.6.litertlm?download=true',
    fileName: 'PaddleOCR-VL-1.6.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen3.5-2b',
    name: 'Qwen3.5-2B',
    tag: 'litert-community',
    size: '2.9 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Qwen3.5-2B/resolve/main/Qwen3.5-2B-VL_int8.litertlm?download=true',
    fileName: 'Qwen3.5-2B-VL_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen3-0.6b',
    name: 'Qwen3-0.6B',
    tag: 'litert-community',
    size: '0.6 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Qwen3-0.6B/resolve/main/Qwen3-0.6B.litertlm?download=true',
    fileName: 'Qwen3-0.6B.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'fastvlm-0.5b',
    name: 'FastVLM-0.5B',
    tag: 'litert-community',
    size: '1.1 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/FastVLM-0.5B/resolve/main/FastVLM-0.5B.litertlm?download=true',
    fileName: 'FastVLM-0.5B.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'functiongemma-mobile-actions_q8_ekv1024.litertlm',
    name: 'functiongemma-mobile-actions_q8_ekv1024.litertlm',
    tag: 'litert-community',
    size: '0.3 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/functiongemma-mobile-actions_q8_ekv1024.litertlm/resolve/main/mobile-actions_q8_ekv1024.litertlm?download=true',
    fileName: 'mobile-actions_q8_ekv1024.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'q8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: true,
    isDraftModel: true
  },
  {
    id: 'tinyswallow-1.5b-instruct',
    name: 'TinySwallow-1.5B-Instruct',
    tag: 'litert-community',
    size: '1.5 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/TinySwallow-1.5B-Instruct/resolve/main/TinySwallow-1.5B-Instruct.litertlm?download=true',
    fileName: 'TinySwallow-1.5B-Instruct.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: true
  },
  {
    id: 'smollm2-360m-instruct',
    name: 'SmolLM2-360M-Instruct',
    tag: 'litert-community',
    size: '0.3 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/SmolLM2-360M-Instruct/resolve/main/SmolLM2_360M_instruct.litertlm?download=true',
    fileName: 'SmolLM2_360M_instruct.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: true
  },
  {
    id: 'qwen3-4b',
    name: 'Qwen3-4B',
    tag: 'litert-community',
    size: '5.3 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Qwen3-4B/resolve/main/qwen3_4b_channelwise_int8_float32kv.litertlm?download=true',
    fileName: 'qwen3_4b_channelwise_int8_float32kv.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 32768,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen3-8b',
    name: 'Qwen3-8B',
    tag: 'litert-community',
    size: '7.7 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Qwen3-8B/resolve/main/qwen3_8b_channelwise_int8_float32kv.litertlm?download=true',
    fileName: 'qwen3_8b_channelwise_int8_float32kv.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 32768,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen3-4b-instruct-2507',
    name: 'Qwen3-4B-Instruct-2507',
    tag: 'litert-community',
    size: '2.5 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Qwen3-4B-Instruct-2507/resolve/main/qwen3_4b_instruct_2507_mixed_int4.litertlm?download=true',
    fileName: 'qwen3_4b_instruct_2507_mixed_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen3-asr-0.6b',
    name: 'Qwen3-ASR-0.6B',
    tag: 'litert-community',
    size: '0.9 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Qwen3-ASR-0.6B/resolve/main/qwen3_asr_0.6b_5s_i8.litertlm?download=true',
    fileName: 'qwen3_asr_0.6b_5s_i8.litertlm',
    badge: 'Audio',
    supportsVision: false,
    supportsAudio: true,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen3-14b',
    name: 'Qwen3-14B',
    tag: 'litert-community',
    size: '13.9 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Qwen3-14B/resolve/main/qwen3_14b_channelwise_int8_float32kv.litertlm?download=true',
    fileName: 'qwen3_14b_channelwise_int8_float32kv.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 32768,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'smollm2-135m-instruct',
    name: 'SmolLM2-135M-Instruct',
    tag: 'litert-community',
    size: '0.1 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/SmolLM2-135M-Instruct/resolve/main/SmolLM2_135M_Instruct.litertlm?download=true',
    fileName: 'SmolLM2_135M_Instruct.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: true
  },
  {
    id: 'vibethinker-1.5b',
    name: 'VibeThinker-1.5B',
    tag: 'litert-community',
    size: '1.5 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/VibeThinker-1.5B/resolve/main/VibeThinker-1.5B.litertlm?download=true',
    fileName: 'VibeThinker-1.5B.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen2-1.5b-instruct',
    name: 'Qwen2-1.5B-Instruct',
    tag: 'litert-community',
    size: '1.7 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Qwen2-1.5B-Instruct/resolve/main/Qwen2_1.5B_Instruct.litertlm?download=true',
    fileName: 'Qwen2_1.5B_Instruct.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'deepseek-r1-distill-qwen-7b',
    name: 'DeepSeek-R1-Distill-Qwen-7B',
    tag: 'litert-community',
    size: '4.2 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/DeepSeek-R1-Distill-Qwen-7B/resolve/main/DeepSeek-R1-Distill-Qwen-7B_q4_block32_ekv4096.litertlm?download=true',
    fileName: 'DeepSeek-R1-Distill-Qwen-7B_q4_block32_ekv4096.litertlm',
    badge: 'Reasoning',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 4096,
    quantization: 'q4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen2-0.5b-instruct',
    name: 'Qwen2-0.5B-Instruct',
    tag: 'litert-community',
    size: '0.6 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Qwen2-0.5B-Instruct/resolve/main/Qwen2_0.5B_Instruct.litertlm?download=true',
    fileName: 'Qwen2_0.5B_Instruct.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen3-1.7b',
    name: 'Qwen3-1.7B',
    tag: 'litert-community',
    size: '0.9 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Qwen3-1.7B/resolve/main/Qwen3-1.7B_dynamic_wi4b32_afp32.litertlm?download=true',
    fileName: 'Qwen3-1.7B_dynamic_wi4b32_afp32.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'ministral-3-3b-instruct-2512',
    name: 'Ministral-3-3B-Instruct-2512',
    tag: 'litert-community',
    size: '2.2 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Ministral-3-3B-Instruct-2512/resolve/main/Ministral-3-3B-Instruct-2512_q4_block32_ekv4096.litertlm?download=true',
    fileName: 'Ministral-3-3B-Instruct-2512_q4_block32_ekv4096.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 4096,
    quantization: 'q4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'olmo-2-1b-instruct',
    name: 'OLMo-2-1B-Instruct',
    tag: 'litert-community',
    size: '0.9 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/OLMo-2-1B-Instruct/resolve/main/OLMo-2-1B-Instruct_q4_block32_ekv4096.litertlm?download=true',
    fileName: 'OLMo-2-1B-Instruct_q4_block32_ekv4096.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 4096,
    quantization: 'q4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'fastcontext-1.0-4b-sft',
    name: 'FastContext-1.0-4B-SFT',
    tag: 'litert-community',
    size: '2.5 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/FastContext-1.0-4B-SFT/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'smollm3-3b',
    name: 'SmolLM3-3B',
    tag: 'litert-community',
    size: '2.9 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/SmolLM3-3B/resolve/main/SmolLM3-3B.litertlm?download=true',
    fileName: 'SmolLM3-3B.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'minicpm5-1b',
    name: 'MiniCPM5-1B',
    tag: 'litert-community',
    size: '1.0 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/MiniCPM5-1B/resolve/main/MiniCPM5-1B_dynamic_wi8_afp32.litertlm?download=true',
    fileName: 'MiniCPM5-1B_dynamic_wi8_afp32.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'jan-nano',
    name: 'Jan-nano',
    tag: 'litert-community',
    size: '2.3 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Jan-nano/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: true
  },
  {
    id: 'internvl3-1b',
    name: 'InternVL3-1B',
    tag: 'litert-community',
    size: '0.7 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/InternVL3-1B/resolve/main/InternVL3-1B.litertlm?download=true',
    fileName: 'InternVL3-1B.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'smolvlm2-500m',
    name: 'SmolVLM2-500M',
    tag: 'litert-community',
    size: '0.3 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/SmolVLM2-500M/resolve/main/SmolVLM2-500M.litertlm?download=true',
    fileName: 'SmolVLM2-500M.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: true
  },
  {
    id: 'vibethinker-3b',
    name: 'VibeThinker-3B',
    tag: 'litert-community',
    size: '1.9 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/VibeThinker-3B/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen3-4b-thinking-2507',
    name: 'Qwen3-4B-Thinking-2507',
    tag: 'litert-community',
    size: '2.1 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Qwen3-4B-Thinking-2507/resolve/main/Qwen3_4b_thinking_dynamic_wi4b32_afp32.litertlm?download=true',
    fileName: 'Qwen3_4b_thinking_dynamic_wi4b32_afp32.litertlm',
    badge: 'Reasoning',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen3-0.6b-int4',
    name: 'Qwen3-0.6B-int4',
    tag: 'litert-community',
    size: '0.3 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Qwen3-0.6B-int4/resolve/main/qwen3_0.6b_nothink_q4_block32_ekv1280.litertlm?download=true',
    fileName: 'qwen3_0.6b_nothink_q4_block32_ekv1280.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1280,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: true
  },
  {
    id: 'llava-onevision-0.5b',
    name: 'LLaVA-OneVision-0.5B',
    tag: 'litert-community',
    size: '0.8 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/LLaVA-OneVision-0.5B/resolve/main/LLaVA-OneVision-0.5B.litertlm?download=true',
    fileName: 'LLaVA-OneVision-0.5B.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'internvl3-2b',
    name: 'InternVL3-2B',
    tag: 'litert-community',
    size: '1.3 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/InternVL3-2B/resolve/main/InternVL3-2B.litertlm?download=true',
    fileName: 'InternVL3-2B.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'phi-4-mini-reasoning',
    name: 'Phi-4-mini-reasoning',
    tag: 'litert-community',
    size: '2.6 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Phi-4-mini-reasoning/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: 'Reasoning',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'nanbeige4.1-3b',
    name: 'Nanbeige4.1-3B',
    tag: 'litert-community',
    size: '2.2 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Nanbeige4.1-3B/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'internvl3_5-2b',
    name: 'InternVL3_5-2B',
    tag: 'litert-community',
    size: '1.5 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/InternVL3_5-2B/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'ovis2.5-2b',
    name: 'Ovis2.5-2B',
    tag: 'litert-community',
    size: '2.0 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Ovis2.5-2B/resolve/main/Ovis2.5-2B.litertlm?download=true',
    fileName: 'Ovis2.5-2B.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'internvl3_5-4b',
    name: 'InternVL3_5-4B',
    tag: 'litert-community',
    size: '2.8 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/InternVL3_5-4B/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'smolvlm2-2.2b',
    name: 'SmolVLM2-2.2B',
    tag: 'litert-community',
    size: '1.4 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/SmolVLM2-2.2B/resolve/main/SmolVLM2-2.2B.litertlm?download=true',
    fileName: 'SmolVLM2-2.2B.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'ministral-3-3b-reasoning-2512',
    name: 'Ministral-3-3B-Reasoning-2512',
    tag: 'litert-community',
    size: '2.2 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Ministral-3-3B-Reasoning-2512/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: 'Reasoning',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'internvl3_5-1b',
    name: 'InternVL3_5-1B',
    tag: 'litert-community',
    size: '0.8 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/InternVL3_5-1B/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'polaris-4b-preview',
    name: 'Polaris-4B-Preview',
    tag: 'litert-community',
    size: '2.3 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Polaris-4B-Preview/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen2-vl-2b',
    name: 'Qwen2-VL-2B',
    tag: 'litert-community',
    size: '1.7 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Qwen2-VL-2B/resolve/main/Qwen2-VL-2B.litertlm?download=true',
    fileName: 'Qwen2-VL-2B.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'lfm2.5-1.2b-instruct',
    name: 'LFM2.5-1.2B-Instruct',
    tag: 'litert-community',
    size: '0.7 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/LFM2.5-1.2B-Instruct/resolve/main/LFM2.5-1.2B-Instruct_int4.litertlm?download=true',
    fileName: 'LFM2.5-1.2B-Instruct_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'granite-4.0-350m-litert-lm',
    name: 'granite-4.0-350m-litert-lm',
    tag: 'litert-community',
    size: '0.4 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/granite-4.0-350m-litert-lm/resolve/main/granite-4.0-350m_q8_ekv1280.litertlm?download=true',
    fileName: 'granite-4.0-350m_q8_ekv1280.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1280,
    quantization: 'q8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: true
  },
  {
    id: 'granite-4.0-h-1b',
    name: 'granite-4.0-h-1b',
    tag: 'litert-community',
    size: '1.6 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/granite-4.0-h-1b/resolve/main/granite-4.0-h-1b_int8.litertlm?download=true',
    fileName: 'granite-4.0-h-1b_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'nanbeige4.2-3b',
    name: 'Nanbeige4.2-3B',
    tag: 'litert-community',
    size: '2.4 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Nanbeige4.2-3B/resolve/main/model.litertlm?download=true',
    fileName: 'model.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'minicpm-v-4',
    name: 'MiniCPM-V-4',
    tag: 'litert-community',
    size: '3.9 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/MiniCPM-V-4/resolve/main/MiniCPM-V-4-int8.litertlm?download=true',
    fileName: 'MiniCPM-V-4-int8.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'granite-4.0-h-350m',
    name: 'granite-4.0-h-350m',
    tag: 'litert-community',
    size: '0.7 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/granite-4.0-h-350m/resolve/main/granite-4.0-h-350m_fp16.litertlm?download=true',
    fileName: 'granite-4.0-h-350m_fp16.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'fp16',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'lfm2.5-1.2b-thinking',
    name: 'LFM2.5-1.2B-Thinking',
    tag: 'litert-community',
    size: '0.7 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/LFM2.5-1.2B-Thinking/resolve/main/LFM2.5-1.2B-Thinking_int4.litertlm?download=true',
    fileName: 'LFM2.5-1.2B-Thinking_int4.litertlm',
    badge: 'Reasoning',
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: true,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'mage-vl',
    name: 'Mage-VL',
    tag: 'litert-community',
    size: '2.6 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Mage-VL/resolve/main/Mage-VL.litertlm?download=true',
    fileName: 'Mage-VL.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'lfm2.5-1.2b-jp',
    name: 'LFM2.5-1.2B-JP',
    tag: 'litert-community',
    size: '0.7 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/LFM2.5-1.2B-JP/resolve/main/LFM2.5-1.2B-JP_int4.litertlm?download=true',
    fileName: 'LFM2.5-1.2B-JP_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen3.5-0.8b',
    name: 'Qwen3.5-0.8B',
    tag: 'litert-community',
    size: '1.2 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Qwen3.5-0.8B/resolve/main/Qwen3.5-0.8B-VL_int8.litertlm?download=true',
    fileName: 'Qwen3.5-0.8B-VL_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'lfm2.5-vl-3b',
    name: 'LFM2.5-VL-3B',
    tag: 'litert-community',
    size: '2.2 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/LFM2.5-VL-3B/resolve/main/LFM2.5-VL-3B_int4.litertlm?download=true',
    fileName: 'LFM2.5-VL-3B_int4.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'lfm2.5-vl-450m',
    name: 'LFM2.5-VL-450M',
    tag: 'litert-community',
    size: '0.4 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/LFM2.5-VL-450M/resolve/main/LFM2.5-VL-450M_int4.litertlm?download=true',
    fileName: 'LFM2.5-VL-450M_int4.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: true
  },
  {
    id: 'nemotron-3-embed-1b',
    name: 'Nemotron-3-Embed-1B',
    tag: 'litert-community',
    size: '1.9 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Nemotron-3-Embed-1B/resolve/main/Nemotron-3-Embed-1B_fp16.litertlm?download=true',
    fileName: 'Nemotron-3-Embed-1B_fp16.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'fp16',
    isEmbedding: true,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'lfm2.5-embedding-350m',
    name: 'LFM2.5-Embedding-350M',
    tag: 'litert-community',
    size: '0.6 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/LFM2.5-Embedding-350M/resolve/main/LFM2.5-Embedding-350M_fp16.litertlm?download=true',
    fileName: 'LFM2.5-Embedding-350M_fp16.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'fp16',
    isEmbedding: true,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'shieldstral-1.0-3b',
    name: 'Shieldstral-1.0-3B',
    tag: 'litert-community',
    size: '2.6 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Shieldstral-1.0-3B/resolve/main/Shieldstral-1.0-3B-vision_int4.litertlm?download=true',
    fileName: 'Shieldstral-1.0-3B-vision_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'lfm2.5-vl-1.6b',
    name: 'LFM2.5-VL-1.6B',
    tag: 'litert-community',
    size: '1.2 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/LFM2.5-VL-1.6B/resolve/main/LFM2.5-VL-1.6B_int4.litertlm?download=true',
    fileName: 'LFM2.5-VL-1.6B_int4.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'lfm2.5-2.6b',
    name: 'LFM2.5-2.6B',
    tag: 'litert-community',
    size: '1.6 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/LFM2.5-2.6B/resolve/main/LFM2.5-2.6B_int4.litertlm?download=true',
    fileName: 'LFM2.5-2.6B_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'falcon-h1-0.5b-instruct',
    name: 'Falcon-H1-0.5B-Instruct',
    tag: 'litert-community',
    size: '0.6 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Falcon-H1-0.5B-Instruct/resolve/main/Falcon-H1-0.5B-Instruct_int8.litertlm?download=true',
    fileName: 'Falcon-H1-0.5B-Instruct_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'nemotron-h-4b-instruct-128k',
    name: 'Nemotron-H-4B-Instruct-128K',
    tag: 'litert-community',
    size: '4.5 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Nemotron-H-4B-Instruct-128K/resolve/main/Nemotron-H-4B-Instruct-128K_int8.litertlm?download=true',
    fileName: 'Nemotron-H-4B-Instruct-128K_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 131072,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'granite-embedding-311m-multilingual-r2',
    name: 'granite-embedding-311m-multilingual-r2',
    tag: 'litert-community',
    size: '0.4 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/granite-embedding-311m-multilingual-r2/resolve/main/granite-embedding-311m-r2_fp16.litertlm?download=true',
    fileName: 'granite-embedding-311m-r2_fp16.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'fp16',
    isEmbedding: true,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: true
  },
  {
    id: 'north-micro-vision-instruct',
    name: 'North-Micro-Vision-Instruct',
    tag: 'litert-community',
    size: '2.0 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/North-Micro-Vision-Instruct/resolve/main/North-Micro-Vision-Instruct_int4.litertlm?download=true',
    fileName: 'North-Micro-Vision-Instruct_int4.litertlm',
    badge: 'Vision',
    supportsVision: true,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'falcon-h1-1.5b-deep-instruct',
    name: 'Falcon-H1-1.5B-Deep-Instruct',
    tag: 'litert-community',
    size: '1.7 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Falcon-H1-1.5B-Deep-Instruct/resolve/main/Falcon-H1-1.5B-Deep-Instruct_int8.litertlm?download=true',
    fileName: 'Falcon-H1-1.5B-Deep-Instruct_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'codegemma-7b-it-int4-litertlm',
    name: 'codegemma-7b-it-int4-litertlm',
    tag: 'litert-community',
    size: '4.4 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/codegemma-7b-it-int4-litertlm/resolve/main/codegemma-7b-it-int4-litertlm.litertlm?download=true',
    fileName: 'codegemma-7b-it-int4-litertlm.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen2.5-coder-1.5b-instruct',
    name: 'Qwen2.5-Coder-1.5B-Instruct',
    tag: 'litert-community',
    size: '1.0 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Qwen2.5-Coder-1.5B-Instruct/resolve/main/Qwen2.5-Coder-1.5B-Instruct_int4.litertlm?download=true',
    fileName: 'Qwen2.5-Coder-1.5B-Instruct_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: true,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'falcon-h1-1.5b-instruct',
    name: 'Falcon-H1-1.5B-Instruct',
    tag: 'litert-community',
    size: '1.6 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Falcon-H1-1.5B-Instruct/resolve/main/Falcon-H1-1.5B-Instruct_int8.litertlm?download=true',
    fileName: 'Falcon-H1-1.5B-Instruct_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'zamba2-1.2b-instruct',
    name: 'Zamba2-1.2B-instruct',
    tag: 'litert-community',
    size: '1.3 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Zamba2-1.2B-instruct/resolve/main/Zamba2-1.2B-instruct_int8.litertlm?download=true',
    fileName: 'Zamba2-1.2B-instruct_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'falcon-h1-3b-instruct',
    name: 'Falcon-H1-3B-Instruct',
    tag: 'litert-community',
    size: '3.2 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Falcon-H1-3B-Instruct/resolve/main/Falcon-H1-3B-Instruct_int8.litertlm?download=true',
    fileName: 'Falcon-H1-3B-Instruct_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'granite-4.1-3b',
    name: 'granite-4.1-3b',
    tag: 'litert-community',
    size: '2.0 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/granite-4.1-3b/resolve/main/granite-4.1-3b_int4.litertlm?download=true',
    fileName: 'granite-4.1-3b_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'qwen3.5-4b',
    name: 'Qwen3.5-4B',
    tag: 'litert-community',
    size: '4.1 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Qwen3.5-4B/resolve/main/Qwen3.5-4B_int8.litertlm?download=true',
    fileName: 'Qwen3.5-4B_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'zamba2-2.7b-instruct',
    name: 'Zamba2-2.7B-instruct',
    tag: 'litert-community',
    size: '2.6 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Zamba2-2.7B-instruct/resolve/main/Zamba2-2.7B-instruct_int8.litertlm?download=true',
    fileName: 'Zamba2-2.7B-instruct_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'smollm2-1.7b-instruct',
    name: 'SmolLM2-1.7B-Instruct',
    tag: 'litert-community',
    size: '1.6 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/SmolLM2-1.7B-Instruct/resolve/main/SmolLM2-1_7B-Instruct_dynamic_wi8_afp32.litertlm?download=true',
    fileName: 'SmolLM2-1_7B-Instruct_dynamic_wi8_afp32.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'hy-mt2-1.8b',
    name: 'Hy-MT2-1.8B',
    tag: 'litert-community',
    size: '1.7 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Hy-MT2-1.8B/resolve/main/Hy-MT2-1.8B_int8.litertlm?download=true',
    fileName: 'Hy-MT2-1.8B_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'falcon-h1-tiny-r-0.6b',
    name: 'Falcon-H1-Tiny-R-0.6B',
    tag: 'litert-community',
    size: '0.8 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Falcon-H1-Tiny-R-0.6B/resolve/main/Falcon-H1-Tiny-R-0.6B_int8.litertlm?download=true',
    fileName: 'Falcon-H1-Tiny-R-0.6B_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: true
  },
  {
    id: 'vibevoice-asr-bitnet',
    name: 'VibeVoice-ASR-BitNet',
    tag: 'litert-community',
    size: '1.8 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/VibeVoice-ASR-BitNet/resolve/main/VibeVoice-ASR-BitNet.litertlm?download=true',
    fileName: 'VibeVoice-ASR-BitNet.litertlm',
    badge: 'Audio',
    supportsVision: false,
    supportsAudio: true,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'sarashina2.2-0.5b-instruct-v0.1',
    name: 'sarashina2.2-0.5b-instruct-v0.1',
    tag: 'litert-community',
    size: '0.5 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/sarashina2.2-0.5b-instruct-v0.1/resolve/main/sarashina2.2-0.5b-instruct-v0.1_int4.litertlm?download=true',
    fileName: 'sarashina2.2-0.5b-instruct-v0.1_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: true
  },
  {
    id: 'sarashina2.2-1b-instruct-v0.1',
    name: 'sarashina2.2-1b-instruct-v0.1',
    tag: 'litert-community',
    size: '0.8 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/sarashina2.2-1b-instruct-v0.1/resolve/main/sarashina2.2-1b-instruct-v0.1_int4.litertlm?download=true',
    fileName: 'sarashina2.2-1b-instruct-v0.1_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'nemotron-3-nano-4b',
    name: 'Nemotron-3-Nano-4B',
    tag: 'litert-community',
    size: '3.8 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Nemotron-3-Nano-4B/resolve/main/Nemotron-3-Nano-4B_int8.litertlm?download=true',
    fileName: 'Nemotron-3-Nano-4B_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: true
  },
  {
    id: 'granite-docling-258m',
    name: 'granite-docling-258M',
    tag: 'litert-community',
    size: '0.3 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/granite-docling-258M/resolve/main/granite-docling-258M.litertlm?download=true',
    fileName: 'granite-docling-258M.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: true
  },
  {
    id: 'granite-4.2-3b',
    name: 'granite-4.2-3b',
    tag: 'litert-community',
    size: '2.0 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/granite-4.2-3b/resolve/main/granite-4.2-3b_int4.litertlm?download=true',
    fileName: 'granite-4.2-3b_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'lfm2.5-230m',
    name: 'LFM2.5-230M',
    tag: 'litert-community',
    size: '0.2 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/LFM2.5-230M/resolve/main/LFM2.5-230M_int4.litertlm?download=true',
    fileName: 'LFM2.5-230M_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: true
  },
  {
    id: 'agents-a1-4b',
    name: 'Agents-A1-4B',
    tag: 'litert-community',
    size: '4.1 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Agents-A1-4B/resolve/main/Agents-A1-4B_int8.litertlm?download=true',
    fileName: 'Agents-A1-4B_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'ternary-bonsai-1.7b',
    name: 'Ternary-Bonsai-1.7B',
    tag: 'litert-community',
    size: '0.7 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Ternary-Bonsai-1.7B/resolve/main/bonsai-1.7b-int2pc-32k-crashfix.litertlm?download=true',
    fileName: 'bonsai-1.7b-int2pc-32k-crashfix.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 32768,
    quantization: 'int2',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'vibevoice-asr-streaming-1.5b',
    name: 'VibeVoice-ASR-Streaming-1.5B',
    tag: 'litert-community',
    size: '1.9 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/VibeVoice-ASR-Streaming-1.5B/resolve/main/VibeVoice-ASR-Streaming-1.5B.litertlm?download=true',
    fileName: 'VibeVoice-ASR-Streaming-1.5B.litertlm',
    badge: 'Audio',
    supportsVision: false,
    supportsAudio: true,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: undefined,
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'embeddinggemma-300m-tensor-g4-npu',
    name: 'EmbeddingGemma-300M-Tensor-G4-NPU',
    tag: 'litert-community',
    size: '0.2 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/EmbeddingGemma-300M-Tensor-G4-NPU/resolve/main/EmbeddingGemma-300M_seq256_Google_Tensor_G4.litertlm?download=true',
    fileName: 'EmbeddingGemma-300M_seq256_Google_Tensor_G4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU','GPU','CPU'],
    maxContextLength: 256,
    quantization: undefined,
    isEmbedding: true,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: true
  },
  {
    id: 'decider-0.8b-litert',
    name: 'decider-0.8b-LiteRT',
    tag: 'litert-community',
    size: '1.5 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/decider-0.8b-LiteRT/resolve/main/decider-0.8b_fp16.litertlm?download=true',
    fileName: 'decider-0.8b_fp16.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'fp16',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'phi-3-mini-4k-instruct',
    name: 'Phi-3-mini-4k-instruct',
    tag: 'litert-community',
    size: '3.6 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Phi-3-mini-4k-instruct/resolve/main/phi3_mini_4k_instruct_int8.litertlm?download=true',
    fileName: 'phi3_mini_4k_instruct_int8.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 4096,
    quantization: 'int8',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'spark-x2.5-1.7b',
    name: 'Spark-X2.5-1.7B',
    tag: 'litert-community',
    size: '1.2 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Spark-X2.5-1.7B/resolve/main/Spark-X2.5-1.7B_int4.litertlm?download=true',
    fileName: 'Spark-X2.5-1.7B_int4.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: 'gemma3-1b-it-tensor-npu',
    name: 'Gemma3-1B-IT-Tensor-NPU',
    tag: 'litert-community',
    size: '0.8 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Gemma3-1B-IT-Tensor-NPU/resolve/main/Gemma3-1B-IT_int4hadamard_aot_ekv4096_G3.litertlm?download=true',
    fileName: 'Gemma3-1B-IT_int4hadamard_aot_ekv4096_G3.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['NPU','GPU','CPU'],
    maxContextLength: 4096,
    quantization: 'int4',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
  {
    id: '1bit-bonsai-1.7b-poc',
    name: '1Bit-Bonsai-1.7B-PoC',
    tag: 'litert-community',
    size: '0.5 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/1Bit-Bonsai-1.7B-PoC/resolve/main/bonsai-1.7b-int1-REAL.litertlm?download=true',
    fileName: 'bonsai-1.7b-int1-REAL.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 1024,
    quantization: 'int1',
    isEmbedding: false,
    isCoder: false,
    isInstruct: true,
    supportsFunctionCalling: false,
    isDraftModel: true
  },
  {
    id: 'ternary-bonsai-8b',
    name: 'Ternary-Bonsai-8B',
    tag: 'litert-community',
    size: '2.4 GB',
    description: 'Automatically discovered LiteRT-LM model from litert-community.',
    url: 'https://huggingface.co/litert-community/Ternary-Bonsai-8B/resolve/main/bonsai-8b-int2pc-32k-crashfix.litertlm?download=true',
    fileName: 'bonsai-8b-int2pc-32k-crashfix.litertlm',
    badge: undefined,
    supportsVision: false,
    supportsAudio: false,
    supportsThinking: false,
    supportedBackends: ['CPU','GPU'],
    maxContextLength: 32768,
    quantization: 'int2',
    isEmbedding: false,
    isCoder: false,
    isInstruct: false,
    supportsFunctionCalling: false,
    isDraftModel: false
  },
];

interface LLMState {
  selectedModelId: string;
  loadedModelId: string | null;
  preferredBackend: BackendType;
  activeBackend: string | null;
  modelStatuses: Record<string, ModelState>;
  isGenerating: boolean;
}

const initialModelStatuses: Record<string, ModelState> = AVAILABLE_MODELS.reduce(
  (acc, model) => {
    acc[model.id] = {
      status: 'not_downloaded',
      progress: 0,
      speedMBs: 0,
      bytesDownloaded: 0,
      totalBytes: 0,
      error: null,
    };
    return acc;
  },
  {} as Record<string, ModelState>
);

const initialState: LLMState = {
  selectedModelId: 'gemma-4-e2b',
  loadedModelId: null,
  preferredBackend: 'AUTO',
  activeBackend: null,
  modelStatuses: initialModelStatuses,
  isGenerating: false,
};

const llmSlice = createSlice({
  name: 'llm',
  initialState,
  reducers: {
    setSelectedModel: (state, action: PayloadAction<string>) => {
      state.selectedModelId = action.payload;
    },
    setPreferredBackend: (state, action: PayloadAction<BackendType>) => {
      state.preferredBackend = action.payload;
    },
    setActiveBackend: (state, action: PayloadAction<string | null>) => {
      state.activeBackend = action.payload;
    },
    startDownload: (state, action: PayloadAction<string>) => {
      const modelId = action.payload;
      state.modelStatuses[modelId] = {
        status: 'downloading',
        progress: 0,
        speedMBs: 0,
        bytesDownloaded: 0,
        totalBytes: 0,
        error: null,
      };
    },
    setDownloadProgress: (
      state,
      action: PayloadAction<{
        modelId: string;
        progress: number;
        speedMBs?: number;
        bytesDownloaded?: number;
        totalBytes?: number;
      }>
    ) => {
      const { modelId, progress, speedMBs, bytesDownloaded, totalBytes } =
        action.payload;
      if (state.modelStatuses[modelId]) {
        state.modelStatuses[modelId].status = 'downloading';
        state.modelStatuses[modelId].progress = progress;
        if (speedMBs !== undefined) state.modelStatuses[modelId].speedMBs = speedMBs;
        if (bytesDownloaded !== undefined)
          state.modelStatuses[modelId].bytesDownloaded = bytesDownloaded;
        if (totalBytes !== undefined)
          state.modelStatuses[modelId].totalBytes = totalBytes;
      }
    },
    setDownloaded: (
      state,
      action: PayloadAction<{ modelId: string; localPath?: string }>
    ) => {
      const { modelId, localPath } = action.payload;
      state.modelStatuses[modelId] = {
        status: 'downloaded',
        progress: 100,
        localPath: localPath || state.modelStatuses[modelId]?.localPath,
        error: null,
      };
    },
    setDownloadError: (
      state,
      action: PayloadAction<{ modelId: string; error: string }>
    ) => {
      const { modelId, error } = action.payload;
      if (state.modelStatuses[modelId]) {
        state.modelStatuses[modelId].status = 'not_downloaded';
        state.modelStatuses[modelId].progress = 0;
        state.modelStatuses[modelId].error = error;
      }
    },
    syncModelStatus: (
      state,
      action: PayloadAction<{
        modelId: string;
        isDownloaded: boolean;
        localPath?: string;
      }>
    ) => {
      const { modelId, isDownloaded, localPath } = action.payload;
      if (state.modelStatuses[modelId]) {
        if (isDownloaded) {
          state.modelStatuses[modelId].status =
            state.loadedModelId === modelId ? 'loaded' : 'downloaded';
          state.modelStatuses[modelId].progress = 100;
          state.modelStatuses[modelId].localPath = localPath;
        } else if (state.modelStatuses[modelId].status !== 'downloading') {
          state.modelStatuses[modelId].status = 'not_downloaded';
          state.modelStatuses[modelId].progress = 0;
        }
      }
    },
    startLoadingModel: (state, action: PayloadAction<string>) => {
      const modelId = action.payload;
      if (state.modelStatuses[modelId]) {
        state.modelStatuses[modelId].status = 'loading';
        state.modelStatuses[modelId].error = null;
      }
    },
    setModelLoadFailed: (
      state,
      action: PayloadAction<{ modelId: string; error: string }>
    ) => {
      // A load attempt only starts once a model is downloaded, so on failure
      // we revert its status back to 'downloaded' (never stuck on 'loading').
      const { modelId, error } = action.payload;
      if (state.modelStatuses[modelId]) {
        state.modelStatuses[modelId].status = 'downloaded';
        state.modelStatuses[modelId].error = error;
      }
      if (state.loadedModelId === modelId) {
        state.loadedModelId = null;
        state.activeBackend = null;
      }
    },
    setLoadedModel: (
      state,
      action: PayloadAction<{ modelId: string; backend?: string }>
    ) => {
      const { modelId, backend } = action.payload;
      if (state.loadedModelId && state.loadedModelId !== modelId) {
        if (state.modelStatuses[state.loadedModelId]?.status === 'loaded') {
          state.modelStatuses[state.loadedModelId].status = 'downloaded';
        }
      }
      state.selectedModelId = modelId;
      state.loadedModelId = modelId;
      if (backend) {
        state.activeBackend = backend;
      }
      if (state.modelStatuses[modelId]) {
        state.modelStatuses[modelId].status = 'loaded';
      }
    },
    deleteModel: (state, action: PayloadAction<string>) => {
      const modelId = action.payload;
      state.modelStatuses[modelId] = {
        status: 'not_downloaded',
        progress: 0,
        speedMBs: 0,
        bytesDownloaded: 0,
        totalBytes: 0,
        localPath: undefined,
        error: null,
      };
      if (state.loadedModelId === modelId) {
        state.loadedModelId = null;
        state.activeBackend = null;
      }
    },
    unloadModel: (state) => {
      if (state.loadedModelId && state.modelStatuses[state.loadedModelId]) {
        state.modelStatuses[state.loadedModelId].status = 'downloaded';
      }
      state.loadedModelId = null;
      state.activeBackend = null;
    },
    setIsGenerating: (state, action: PayloadAction<boolean>) => {
      state.isGenerating = action.payload;
    },
  },
});

export const {
  setSelectedModel,
  setPreferredBackend,
  setActiveBackend,
  startDownload,
  setDownloadProgress,
  setDownloaded,
  setDownloadError,
  syncModelStatus,
  startLoadingModel,
  setModelLoadFailed,
  setLoadedModel,
  deleteModel,
  unloadModel,
  setIsGenerating,
} = llmSlice.actions;

export default llmSlice.reducer;
